/**
 * Linux/systemd server install.
 *
 * Side effects go through InstallHost. TLS and the 0.x store are generated by
 * loadOrCreateTls, NmzpStore.load, and bootstrapAdmin inside a root-owned seed
 * directory, then copied. Existing tls material and admin.token are never
 * overwritten. Trust for "this install created the tree" lives in root-owned
 * /etc/nmzp/install-state.json, not in the nmzp-writable data directory.
 *
 * Residual risk: Node has no openat2. After this process closes a directory fd,
 * nmzp (who owns the data directory) can still replace a child such as tls/
 * before the next open. Ancestors of --data are rejected unless they are
 * root-owned and not group/world writable, which closes that swap above the
 * data directory.
 */
import { execFile } from "node:child_process";
import { createPrivateKey, randomUUID, X509Certificate } from "node:crypto";
import { constants, statfsSync } from "node:fs";
import {
  chmod as chmodAsync,
  lstat,
  mkdir,
  mkdtemp,
  open,
  readFile,
  readdir,
  rename as renameAsync,
  rm,
  writeFile as writeFileAsync,
  type FileHandle,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createServer } from "node:net";
import { newSecret, sha256Hex } from "./auth.ts";
import type { CustomPrivacyRule } from "./schema.ts";
import { certificateCovers, fingerprintSha256Pem } from "./tls.ts";

export const MIN_INSTALL_FREE_BYTES = 1024 * 1024 * 1024;
export const INSTALL_PORTS = [8787, 8788] as const;
export const DEFAULT_DATA_DIR = "/var/lib/nmzp";
export const DEFAULT_PREFIX = "/opt/nmzp";
export const UNIT_PATH = "/etc/systemd/system/nmzp.service";
export const INSTALL_STATE_DIR = "/etc/nmzp";
export const INSTALL_STATE_PATH = "/etc/nmzp/install-state.json";
/** Seed dirs are created here so TMPDIR cannot redirect them. */
export const INSTALL_SEED_PARENT = "/tmp";
/** Linux system accounts: 1 <= id < SYSTEM_ID_LIMIT. */
export const SYSTEM_ID_MIN = 1;
export const SYSTEM_ID_LIMIT = 1000;
export const NMZP_HOME = "/nonexistent";
export const NMZP_USERADD_ARGS = [
  "--system",
  "--gid",
  "nmzp",
  "--no-create-home",
  "--home-dir",
  NMZP_HOME,
  "--shell",
  "/usr/sbin/nologin",
  "nmzp",
] as const;
export const INSTALL_USAGE =
  "usage: nmzp install [--public-url URL] [--data DIR] [--prefix DIR] [--plan]";

const INSTALLER = "nmzp-server-install";
const GETENT = "/usr/bin/getent";
const GROUPADD = "/usr/sbin/groupadd";
const USERADD = "/usr/sbin/useradd";
const SYSTEMCTL = "/usr/bin/systemctl";
const ADMIN_HINT = "admin 口令可以用 `nmzp admin reset-credential` 重置";
const CA_HINT =
  "CA 私钥丢失后不可恢复，所有设备都要重新 join，所以请立即执行 `nmzp backup` 与 `nmzp backup verify`";
const NMZP_SHELLS = new Set<string>(["/usr/sbin/nologin", "/bin/false"]);
const DATA_FILES = [
  "policy.json",
  "devices.json",
  "events.jsonl",
  "network.jsonl",
  "meta.json",
  "admin.token",
] as const;
const TLS_FILES = ["server.key", "server.crt", "pin.json"] as const;

export class InstallError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InstallError";
  }
}

export interface HostStat {
  type: "file" | "dir" | "symlink" | "other";
  /** Permission bits only (mode & 0o777). Sticky/setuid/setgid live in `special`. */
  mode: number;
  uid: number;
  gid: number;
  dev: number;
  ino: number;
  /** Setuid/setgid/sticky (mode & 0o7000). */
  special: number;
}

export interface RunResult {
  status: number;
  stdout: string;
  stderr: string;
}

export interface OpenFileFlags {
  write: boolean;
  create: boolean;
  exclusive: boolean;
  mode: number;
}

/** Fd-relative operations. chmod/chown apply to the opened inode, not a path lookup. */
export interface OpenedPath {
  stat(): Promise<HostStat>;
  chmod(mode: number): Promise<void>;
  chown(uid: number, gid: number): Promise<void>;
  write(data: Buffer | string): Promise<void>;
  read(): Promise<Buffer>;
  fsync(): Promise<void>;
  close(): Promise<void>;
}

export interface InstallHost {
  readonly platform: NodeJS.Platform;
  readonly arch: string;
  isRoot(): boolean;
  freeBytes(path: string): Promise<number>;
  portFree(port: number): Promise<boolean>;
  lstat(path: string): Promise<HostStat | null>;
  mkdir(path: string, mode: number): Promise<void>;
  openFile(path: string, flags: OpenFileFlags): Promise<OpenedPath>;
  openDir(path: string): Promise<OpenedPath>;
  writeFile(path: string, data: Buffer | string, mode: number): Promise<void>;
  readFile(path: string): Promise<Buffer | null>;
  chmod(path: string, mode: number): Promise<void>;
  chown(path: string, uid: number, gid: number): Promise<void>;
  rename(from: string, to: string, overwrite?: boolean): Promise<void>;
  remove(path: string): Promise<void>;
  run(cmd: string, args: readonly string[]): Promise<RunResult>;
  now(): number;
  /** Real directory for generators that write through node:fs (NmzpStore, loadOrCreateTls). */
  generatorDir(): Promise<string>;
  discardGeneratorDir(path: string): Promise<void>;
  /** Path runDoctor can read. Production returns path unchanged. */
  resolve(path: string): string;
}

export interface InstallArgs {
  plan: boolean;
  publicUrl?: string;
  dataDir: string;
  prefix: string;
}

export interface InstallIo {
  host: InstallHost;
  coreDir: string;
  env: NodeJS.ProcessEnv;
  stdout(text: string): void;
  stderr(text: string): void;
}

interface InstallState {
  v: 1;
  installer: typeof INSTALLER;
  dataDir: string;
  prefix: string;
  publicUrl: string | null;
  uid: number;
  gid: number;
  tokenShown: boolean;
  serviceEnabled: boolean;
}

type LoadedState =
  | { kind: "absent" }
  | { kind: "ok"; state: InstallState }
  | { kind: "mismatch"; dataDir: string }
  | { kind: "invalid"; message: string };

interface PasswdRow {
  uid: number;
  gid: number;
  shell: string;
}

interface GroupRow {
  name: string;
  gid: number;
}

export interface UnitEntry {
  key: string;
  value: string;
}

export interface UnitModel {
  sections: Array<{ name: string; entries: UnitEntry[] }>;
}

interface FsNode {
  type: HostStat["type"];
  mode: number;
  uid: number;
  gid: number;
  dev: number;
  ino: number;
  special: number;
  data?: Buffer;
}

interface SeedIdentity {
  dev: number;
  ino: number;
}

export function isSystemAccountId(id: number): boolean {
  return Number.isInteger(id) && id >= SYSTEM_ID_MIN && id < SYSTEM_ID_LIMIT;
}

export function assertSeedParent(stat: HostStat): void {
  if (stat.type !== "dir") throw new InstallError("seed parent is not a directory");
  if ((stat.special & 0o1000) === 0) throw new InstallError("/tmp is not sticky");
}

export function assertSeedDir(stat: HostStat): void {
  if (stat.type !== "dir") throw new InstallError("seed dir is not a directory");
  if (stat.uid !== 0 || stat.gid !== 0) throw new InstallError("seed dir is not root-owned");
  if ((stat.mode & 0o777) !== 0o700) throw new InstallError("seed dir mode is not 0700");
}

export function parseInstallArgs(
  argv: readonly string[],
): { ok: true; value: InstallArgs } | { ok: false; error: string } {
  let plan = false;
  let publicUrl: string | undefined;
  let dataDir = DEFAULT_DATA_DIR;
  let prefix = DEFAULT_PREFIX;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--plan") {
      plan = true;
      continue;
    }
    if (arg === "--public-url" || arg === "--data" || arg === "--prefix") {
      const value = argv[i + 1];
      if (!value || value.startsWith("-")) return { ok: false, error: INSTALL_USAGE };
      i += 1;
      if (arg === "--public-url") publicUrl = value;
      if (arg === "--data") dataDir = value;
      if (arg === "--prefix") prefix = value;
      continue;
    }
    return { ok: false, error: INSTALL_USAGE };
  }
  return { ok: true, value: { plan, publicUrl, dataDir, prefix } };
}

export function parseSystemdUnit(text: string): UnitModel {
  const sections: UnitModel["sections"] = [];
  let current: UnitModel["sections"][number] | undefined;
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || line.startsWith(";")) continue;
    const section = /^\[([A-Za-z]+)\]$/.exec(line);
    if (section) {
      current = { name: section[1] ?? "", entries: [] };
      sections.push(current);
      continue;
    }
    const eq = line.indexOf("=");
    if (!current || eq <= 0) throw new InstallError("invalid systemd unit");
    current.entries.push({ key: line.slice(0, eq), value: line.slice(eq + 1) });
  }
  return { sections };
}

export function unitValues(model: UnitModel, section: string, key: string): string[] {
  return model.sections
    .filter((item) => item.name === section)
    .flatMap((item) =>
      item.entries.filter((entry) => entry.key === key).map((entry) => entry.value),
    );
}

export function renderServiceUnit(
  template: string,
  opts: { dataDir: string; prefix: string },
): string {
  const text = template.replace(/\r\n/g, "\n");
  for (const key of [
    "NoNewPrivileges=true",
    "ProtectSystem=strict",
    "User=nmzp",
    "PrivateTmp=true",
  ]) {
    if (!new RegExp(`^${key}$`, "m").test(text))
      throw new InstallError(`unit template missing ${key}`);
  }
  let next = replaceLine(text, "Environment=NMZP_DATA=", `Environment=NMZP_DATA=${opts.dataDir}`);
  next = replaceLine(next, "ReadWritePaths=", `ReadWritePaths=${opts.dataDir}`);
  next = replaceLine(next, "WorkingDirectory=", `WorkingDirectory=${opts.prefix}`);
  next = replaceLine(next, "ReadOnlyPaths=", `ReadOnlyPaths=${opts.prefix}`);
  const exec = /^ExecStart=(\S+)\s+(--experimental-strip-types)\s+\S+\s+serve\s*$/m.exec(next);
  if (!exec) throw new InstallError("unit template ExecStart is not the 0.x node command");
  next = next.replace(
    /^ExecStart=.*$/m,
    `ExecStart=${exec[1]} ${exec[2]} ${opts.prefix}/nmzp.mjs serve`,
  );
  return next;
}

export async function runServerInstall(args: InstallArgs, io: InstallIo): Promise<number> {
  if (io.host.platform === "win32") {
    io.stderr("Windows server install is WP-60\n");
    return 1;
  }
  const checked = await preflight(args, io.host);
  if (!checked.ok) {
    io.stderr(`${checked.message}\n`);
    return 1;
  }
  if (args.plan || !io.host.isRoot()) {
    for (const line of planLines(args)) io.stdout(`${line}\n`);
    if (!io.host.isRoot() && !args.plan) {
      io.stderr("install requires root\n");
      return 1;
    }
    return 0;
  }
  return execute(args, io);
}

export function createNodeInstallHost(): InstallHost {
  return new NodeInstallHost();
}

export class RecordingInstallHost implements InstallHost {
  readonly platform: NodeJS.Platform;
  readonly arch: string;
  readonly root: string;
  rootUser: boolean;
  free: number;
  readonly ports = new Map<number, boolean>();
  nowMs: number;
  readonly commands: Array<{ cmd: string; args: string[] }> = [];
  readonly mutations: string[] = [];
  /** uid/gid returned after a simulated useradd, unless idsAfterCreate overrides it. */
  readonly ids = { uid: 960, gid: 960 };
  groupPresent = false;
  userPresent = false;
  shell = "/usr/sbin/nologin";
  /** Applied to the getent passwd line. Null uses ids.gid. */
  passwdGid: number | null = null;
  shellAfterCreate: string | null = null;
  idsAfterCreate: { uid: number; gid: number } | null = null;
  failStop = false;
  /** When openFile/openDir hits this path, replace the inode first (lstat/open race). */
  swapOnOpen: string | null = null;
  /** Modeled /tmp. Tests can clear `special` to drop the sticky bit. */
  seedParent: HostStat = {
    type: "dir",
    mode: 0o777,
    uid: 0,
    gid: 0,
    dev: 1,
    ino: 1,
    special: 0o1000,
  };
  /** When set, generatorDir checks this stat with assertSeedDir before creating a real dir. */
  modelSeed: HostStat | null = null;
  private readonly files = new Map<string, FsNode>();
  private readonly seeds = new Map<string, SeedIdentity>();
  private nextIno = 1;

  constructor(opts: {
    root: string;
    platform?: NodeJS.Platform;
    arch?: string;
    rootUser?: boolean;
    free?: number;
    nowMs?: number;
  }) {
    this.root = opts.root;
    this.platform = opts.platform ?? "linux";
    this.arch = opts.arch ?? "x64";
    this.rootUser = opts.rootUser ?? true;
    this.free = opts.free ?? MIN_INSTALL_FREE_BYTES * 2;
    this.nowMs = opts.nowMs ?? 1_700_000_000_000;
  }

  isRoot(): boolean {
    return this.rootUser;
  }

  async freeBytes(): Promise<number> {
    return this.free;
  }

  async portFree(port: number): Promise<boolean> {
    return this.ports.get(port) !== false;
  }

  async lstat(path: string): Promise<HostStat | null> {
    const found = this.files.get(logical(path));
    if (!found) return null;
    return statOf(found);
  }

  async mkdir(path: string, mode: number): Promise<void> {
    const key = logical(path);
    if (this.files.has(key)) throw new InstallError(`mkdir exists: ${key}`);
    const node: FsNode = {
      type: "dir",
      mode: mode & 0o777,
      uid: 0,
      gid: 0,
      dev: 1,
      ino: this.allocIno(),
      special: 0,
    };
    this.files.set(key, node);
    await mkdir(this.disk(key), { recursive: true });
    this.mutations.push(`mkdir ${key} ${mode & 0o777}`);
  }

  async openFile(path: string, flags: OpenFileFlags): Promise<OpenedPath> {
    const key = logical(path);
    this.maybeSwap(key);
    let node = this.files.get(key);
    if (node?.type === "symlink") throw new InstallError(`refusing symlink at ${key}`);
    if (!node && flags.create) {
      node = {
        type: "file",
        mode: flags.mode & 0o777,
        uid: 0,
        gid: 0,
        dev: 1,
        ino: this.allocIno(),
        special: 0,
        data: Buffer.alloc(0),
      };
      this.files.set(key, node);
      await this.persist(key, node);
      return this.opened(node, key);
    }
    if (!node) throw new InstallError(`ENOENT ${key}`);
    if (flags.exclusive) throw new InstallError(`refusing existing path ${key}`);
    if (node.type !== "file") throw new InstallError(`not a file: ${key}`);
    return this.opened(node, key);
  }

  async openDir(path: string): Promise<OpenedPath> {
    const key = logical(path);
    this.maybeSwap(key);
    const node = this.files.get(key);
    if (!node) throw new InstallError(`ENOENT ${key}`);
    if (node.type === "symlink") throw new InstallError(`refusing symlink at ${key}`);
    if (node.type !== "dir") throw new InstallError(`${key} is not a directory`);
    return this.opened(node, key);
  }

  async writeFile(path: string, data: Buffer | string, mode: number): Promise<void> {
    const key = logical(path);
    const body = Buffer.from(data);
    const previous = this.files.get(key);
    if (previous?.type === "symlink") throw new InstallError(`refusing symlink at ${key}`);
    if (previous && previous.type !== "file") throw new InstallError(`not a file: ${key}`);
    const node: FsNode = previous ?? {
      type: "file",
      mode: mode & 0o777,
      uid: 0,
      gid: 0,
      dev: 1,
      ino: this.allocIno(),
      special: 0,
    };
    node.type = "file";
    node.mode = mode & 0o777;
    node.uid = 0;
    node.gid = 0;
    node.data = body;
    this.files.set(key, node);
    await this.persist(key, node);
    this.mutations.push(`write ${key} ${mode & 0o777}`);
  }

  async readFile(path: string): Promise<Buffer | null> {
    return readVerified(this, path);
  }

  /** Test setup only. Install mutations chmod the opened inode. */
  async chmod(path: string, mode: number): Promise<void> {
    const key = logical(path);
    const found = this.files.get(key);
    if (!found) throw new InstallError(`chmod missing: ${key}`);
    found.mode = mode & 0o777;
    try {
      await chmodAsync(this.disk(key), mode & 0o777);
    } catch {
      /* The map is the permission record. Windows does not have these mode bits. */
    }
    this.mutations.push(`chmod ${key} ${mode & 0o777}`);
  }

  /** Test setup only. Install mutations chown the opened inode. */
  async chown(path: string, uid: number, gid: number): Promise<void> {
    const key = logical(path);
    const found = this.files.get(key);
    if (!found) throw new InstallError(`chown missing: ${key}`);
    found.uid = uid;
    found.gid = gid;
    this.mutations.push(`chown ${key} ${uid} ${gid}`);
  }

  async rename(from: string, to: string, overwrite = false): Promise<void> {
    const source = logical(from);
    const dest = logical(to);
    const found = this.files.get(source);
    if (!found) throw new InstallError(`rename missing: ${source}`);
    if (this.files.has(dest)) {
      if (!overwrite) throw new InstallError(`rename target exists: ${dest}`);
      this.files.delete(dest);
      await rm(this.disk(dest), { force: true });
    }
    this.files.set(dest, found);
    this.files.delete(source);
    await mkdir(dirname(this.disk(dest)), { recursive: true });
    await renameAsync(this.disk(source), this.disk(dest));
    this.mutations.push(`rename ${source} ${dest}`);
  }

  async remove(path: string): Promise<void> {
    const key = logical(path);
    const found = this.files.get(key);
    if (!found) return;
    if (found.type !== "file") throw new InstallError(`refusing to remove ${key}`);
    this.files.delete(key);
    await rm(this.disk(key), { force: true });
  }

  async run(cmd: string, args: readonly string[]): Promise<RunResult> {
    const copy = [...args];
    this.commands.push({ cmd, args: copy });
    this.mutations.push(`run ${cmd} ${copy.join(" ")}`);
    return this.simulate(cmd, copy);
  }

  now(): number {
    return this.nowMs;
  }

  async generatorDir(): Promise<string> {
    assertSeedParent(this.seedParent);
    const modeled = this.modelSeed ?? {
      type: "dir" as const,
      mode: 0o700,
      uid: 0,
      gid: 0,
      dev: 1,
      ino: 1,
      special: 0,
    };
    assertSeedDir(modeled);
    const dir = await mkdtemp(join(tmpdir(), "nmzp-install-seed-"));
    const st = await lstat(dir);
    if (st.isSymbolicLink() || !st.isDirectory()) {
      await rm(dir, { recursive: true, force: true });
      throw new InstallError("seed dir is not a directory");
    }
    this.seeds.set(dir, { dev: Number(st.dev), ino: Number(st.ino) });
    this.mutations.push("generator");
    return dir;
  }

  async discardGeneratorDir(path: string): Promise<void> {
    const saved = this.seeds.get(path);
    if (!saved) throw new InstallError("refusing to remove unknown generator dir");
    let st;
    try {
      st = await lstat(path);
    } catch {
      throw new InstallError("seed dir changed");
    }
    if (
      st.isSymbolicLink() ||
      !st.isDirectory() ||
      Number(st.dev) !== saved.dev ||
      Number(st.ino) !== saved.ino
    ) {
      throw new InstallError("seed dir changed");
    }
    await rm(path, { recursive: true, force: true });
    this.seeds.delete(path);
    this.mutations.push("discard-generator");
  }

  /** Next discard of this seed sees a different inode and must refuse to delete it. */
  mismatchSeed(path: string): void {
    const saved = this.seeds.get(path);
    if (!saved) throw new InstallError("unknown seed");
    // Windows file indexes do not fit in a safe integer, so adding 1 can be a no-op.
    saved.ino = -1;
  }

  /** Replace the directory entry so a handle opened earlier still refers to the old inode. */
  retarget(path: string): void {
    const key = logical(path);
    const cur = this.files.get(key);
    if (!cur) return;
    const next: FsNode = {
      type: cur.type,
      mode: 0o777,
      uid: 99,
      gid: 99,
      dev: cur.dev,
      ino: this.allocIno(),
      special: 0,
      data: cur.data ? Buffer.from(cur.data) : undefined,
    };
    this.files.set(key, next);
  }

  resolve(path: string): string {
    return this.disk(logical(path));
  }

  symlink(path: string, target: string): void {
    this.files.set(logical(path), {
      type: "symlink",
      mode: 0o777,
      uid: 0,
      gid: 0,
      dev: 1,
      ino: this.allocIno(),
      special: 0,
      data: Buffer.from(target),
    });
  }

  entries(): Array<{
    path: string;
    type: HostStat["type"];
    mode: number;
    uid: number;
    gid: number;
  }> {
    return [...this.files.keys()].sort().map((path) => {
      const found = this.files.get(path);
      if (!found) throw new InstallError("missing entry");
      return { path, type: found.type, mode: found.mode, uid: found.uid, gid: found.gid };
    });
  }

  private allocIno(): number {
    this.nextIno += 1;
    return this.nextIno;
  }

  private maybeSwap(key: string): void {
    if (this.swapOnOpen === key) this.retarget(key);
  }

  private disk(key: string): string {
    return join(this.root, ...key.slice(1).split("/"));
  }

  private async persist(key: string, node: FsNode): Promise<void> {
    const disk = this.disk(key);
    if (node.type === "dir") {
      await mkdir(disk, { recursive: true });
      try {
        await chmodAsync(disk, node.mode & 0o777);
      } catch {
        /* Windows does not have these mode bits. */
      }
      return;
    }
    await mkdir(dirname(disk), { recursive: true });
    await writeFileAsync(disk, node.data ?? Buffer.alloc(0));
    try {
      await chmodAsync(disk, node.mode & 0o777);
    } catch {
      /* Windows does not have these mode bits. */
    }
  }

  private opened(node: FsNode, key: string): OpenedPath {
    return {
      stat: async () => statOf(node),
      chmod: async (mode: number) => {
        node.mode = mode & 0o777;
        await this.persist(key, node);
        this.mutations.push(`chmod ${key} ${mode & 0o777}`);
      },
      chown: async (uid: number, gid: number) => {
        node.uid = uid;
        node.gid = gid;
        this.mutations.push(`chown ${key} ${uid} ${gid}`);
      },
      write: async (data: Buffer | string) => {
        if (node.type !== "file") throw new InstallError(`not a file: ${key}`);
        node.data = Buffer.from(data);
        await this.persist(key, node);
        this.mutations.push(`write ${key} ${node.mode & 0o777}`);
      },
      read: async () => Buffer.from(node.data ?? Buffer.alloc(0)),
      fsync: async () => {
        this.mutations.push(`fsync ${key}`);
      },
      close: async () => undefined,
    };
  }

  private simulate(cmd: string, args: string[]): RunResult {
    if (cmd === GETENT && sameArgs(args, ["group", "nmzp"])) {
      if (!this.groupPresent) return { status: 2, stdout: "", stderr: "" };
      return { status: 0, stdout: `nmzp:x:${this.ids.gid}:\n`, stderr: "" };
    }
    if (cmd === GROUPADD && sameArgs(args, ["--system", "nmzp"])) {
      this.groupPresent = true;
      return { status: 0, stdout: "", stderr: "" };
    }
    if (cmd === GETENT && sameArgs(args, ["passwd", "nmzp"])) {
      if (!this.userPresent) return { status: 2, stdout: "", stderr: "" };
      const gid = this.passwdGid ?? this.ids.gid;
      return {
        status: 0,
        stdout: `nmzp:x:${this.ids.uid}:${gid}::${NMZP_HOME}:${this.shell}\n`,
        stderr: "",
      };
    }
    if (cmd === USERADD && sameArgs(args, NMZP_USERADD_ARGS)) {
      this.userPresent = true;
      if (this.idsAfterCreate) {
        this.ids.uid = this.idsAfterCreate.uid;
        this.ids.gid = this.idsAfterCreate.gid;
      }
      if (this.shellAfterCreate) this.shell = this.shellAfterCreate;
      return { status: 0, stdout: "", stderr: "" };
    }
    if (cmd === SYSTEMCTL && sameArgs(args, ["stop", "nmzp"])) {
      if (this.failStop) return { status: 1, stdout: "", stderr: "stop failed" };
      return { status: 0, stdout: "", stderr: "" };
    }
    if (
      cmd === SYSTEMCTL &&
      (sameArgs(args, ["daemon-reload"]) || sameArgs(args, ["enable", "--now", "nmzp"]))
    ) {
      return { status: 0, stdout: "", stderr: "" };
    }
    return { status: 127, stdout: "", stderr: "unexpected command" };
  }
}

class NodeOpened implements OpenedPath {
  private readonly handle: FileHandle;

  constructor(handle: FileHandle) {
    this.handle = handle;
  }

  async stat(): Promise<HostStat> {
    return toHostStat(await this.handle.stat());
  }

  async chmod(mode: number): Promise<void> {
    await this.handle.chmod(mode & 0o777);
  }

  async chown(uid: number, gid: number): Promise<void> {
    await this.handle.chown(uid, gid);
  }

  async write(data: Buffer | string): Promise<void> {
    const body = Buffer.from(data);
    await this.handle.truncate(0);
    const result = await this.handle.write(body, 0, body.length, 0);
    if (result.bytesWritten !== body.length) throw new InstallError("short write");
  }

  async read(): Promise<Buffer> {
    const data = await this.handle.readFile();
    return Buffer.isBuffer(data) ? data : Buffer.from(data);
  }

  async fsync(): Promise<void> {
    await this.handle.sync();
  }

  async close(): Promise<void> {
    await this.handle.close();
  }
}

class NodeInstallHost implements InstallHost {
  readonly platform = process.platform;
  readonly arch = process.arch;
  private readonly seeds = new Map<string, SeedIdentity>();

  isRoot(): boolean {
    return (
      process.platform !== "win32" && typeof process.getuid === "function" && process.getuid() === 0
    );
  }

  async freeBytes(path: string): Promise<number> {
    let current = path;
    for (;;) {
      try {
        await lstat(current);
        const stat = statfsSync(current);
        const free = Number(stat.bavail) * Number(stat.bsize);
        if (!Number.isFinite(free) || free < 0) throw new InstallError("free space unavailable");
        return free;
      } catch (error) {
        if (error instanceof InstallError) throw error;
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
        const parent = dirname(current);
        if (parent === current) throw new InstallError("free space unavailable");
        current = parent;
      }
    }
  }

  portFree(port: number): Promise<boolean> {
    return new Promise((resolve) => {
      const server = createServer();
      server.unref();
      let settled = false;
      const finish = (value: boolean) => {
        if (settled) return;
        settled = true;
        if (server.listening) server.close(() => resolve(value));
        else resolve(value);
      };
      server.once("error", () => finish(false));
      server.listen({ port, host: "0.0.0.0", exclusive: true }, () => finish(true));
    });
  }

  async lstat(path: string): Promise<HostStat | null> {
    try {
      return toHostStat(await lstat(path));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw error;
    }
  }

  async mkdir(path: string, mode: number): Promise<void> {
    const existing = await this.lstat(path);
    if (existing?.type === "symlink") throw new InstallError(`refusing symlink at ${path}`);
    if (existing) throw new InstallError(`mkdir exists: ${path}`);
    await mkdir(path, { mode });
  }

  async openFile(path: string, flags: OpenFileFlags): Promise<OpenedPath> {
    const bits = linuxFileFlags(flags);
    try {
      const handle = await open(path, bits, flags.mode & 0o777);
      return new NodeOpened(handle);
    } catch (error) {
      throw mapOpenError(path, error);
    }
  }

  async openDir(path: string): Promise<OpenedPath> {
    try {
      const handle = await open(path, linuxDirFlags());
      return new NodeOpened(handle);
    } catch (error) {
      throw mapOpenError(path, error);
    }
  }

  async writeFile(path: string, data: Buffer | string, mode: number): Promise<void> {
    await writeOwned(this, path, data, mode, 0, 0);
  }

  async readFile(path: string): Promise<Buffer | null> {
    return readVerified(this, path);
  }

  async chmod(path: string, mode: number): Promise<void> {
    const before = await this.lstat(path);
    if (!before || before.type === "symlink") throw new InstallError(`refusing symlink at ${path}`);
    const handle =
      before.type === "dir"
        ? await this.openDir(path)
        : await this.openFile(path, { write: false, create: false, exclusive: false, mode });
    try {
      const st = await handle.stat();
      if (st.dev !== before.dev || st.ino !== before.ino) {
        throw new InstallError(`inode changed at ${path}`);
      }
      await handle.chmod(mode & 0o777);
    } finally {
      await handle.close();
    }
  }

  async chown(path: string, uid: number, gid: number): Promise<void> {
    const before = await this.lstat(path);
    if (!before || before.type === "symlink") throw new InstallError(`refusing symlink at ${path}`);
    const handle =
      before.type === "dir"
        ? await this.openDir(path)
        : await this.openFile(path, { write: false, create: false, exclusive: false, mode: before.mode });
    try {
      const st = await handle.stat();
      if (st.dev !== before.dev || st.ino !== before.ino) {
        throw new InstallError(`inode changed at ${path}`);
      }
      await handle.chown(uid, gid);
    } finally {
      await handle.close();
    }
  }

  async rename(from: string, to: string, overwrite = false): Promise<void> {
    if (!overwrite && (await this.lstat(to))) throw new InstallError(`rename target exists: ${to}`);
    await renameAsync(from, to);
  }

  async remove(path: string): Promise<void> {
    const st = await this.lstat(path);
    if (!st) return;
    if (st.type !== "file") throw new InstallError(`refusing to remove ${path}`);
    await rm(path, { force: true });
  }

  run(cmd: string, args: readonly string[]): Promise<RunResult> {
    if (!cmd.startsWith("/") || cmd.includes("\0") || args.some((arg) => arg.includes("\0"))) {
      return Promise.resolve({ status: 127, stdout: "", stderr: "refusing command" });
    }
    return new Promise((resolve) => {
      execFile(
        cmd,
        [...args],
        { windowsHide: true, timeout: 30_000, maxBuffer: 1024 * 1024 },
        (error, stdout, stderr) => {
          const code =
            error && typeof error === "object" && "code" in error ? error.code : error ? 1 : 0;
          resolve({
            status: typeof code === "number" ? code : 127,
            stdout: String(stdout ?? ""),
            stderr: String(stderr ?? ""),
          });
        },
      );
    });
  }

  now(): number {
    return Date.now();
  }

  async generatorDir(): Promise<string> {
    if (process.platform !== "linux") throw new InstallError("seed dir requires linux");
    const parent = await lstat(INSTALL_SEED_PARENT);
    if (parent.isSymbolicLink()) throw new InstallError("seed parent is not a directory");
    assertSeedParent(toHostStat(parent));
    const dir = await mkdtemp(join(INSTALL_SEED_PARENT, "nmzp-install-seed-"));
    try {
      const st = await lstat(dir);
      if (st.isSymbolicLink()) throw new InstallError("seed dir is not a directory");
      const hostStat = toHostStat(st);
      assertSeedDir(hostStat);
      this.seeds.set(dir, { dev: hostStat.dev, ino: hostStat.ino });
      return dir;
    } catch (error) {
      await rm(dir, { recursive: true, force: true }).catch(() => undefined);
      throw error;
    }
  }

  async discardGeneratorDir(path: string): Promise<void> {
    const saved = this.seeds.get(path);
    if (!saved || !isSeedPath(path)) throw new InstallError("refusing to remove unknown generator dir");
    const st = await lstat(path);
    if (st.isSymbolicLink()) throw new InstallError("seed dir changed");
    const hostStat = toHostStat(st);
    if (hostStat.type !== "dir" || hostStat.dev !== saved.dev || hostStat.ino !== saved.ino) {
      throw new InstallError("seed dir changed");
    }
    assertSeedDir(hostStat);
    await rm(path, { recursive: true, force: true });
    this.seeds.delete(path);
  }

  resolve(path: string): string {
    return path;
  }
}

async function preflight(
  args: InstallArgs,
  host: InstallHost,
): Promise<{ ok: true } | { ok: false; message: string }> {
  try {
    return await preflightInner(args, host);
  } catch (error) {
    if (error instanceof InstallError) return { ok: false, message: error.message };
    throw error;
  }
}

async function preflightInner(
  args: InstallArgs,
  host: InstallHost,
): Promise<{ ok: true } | { ok: false; message: string }> {
  if (host.platform !== "linux" || (host.arch !== "x64" && host.arch !== "arm64")) {
    return { ok: false, message: "nmzp install supports linux x64/arm64 only" };
  }
  if (!isSafeAbs(args.dataDir)) return { ok: false, message: "--data must be an absolute path" };
  if (!isSafeAbs(args.prefix)) return { ok: false, message: "--prefix must be an absolute path" };
  const publicHost = args.publicUrl === undefined ? undefined : httpsHost(args.publicUrl);
  if (args.publicUrl !== undefined && !publicHost) {
    return { ok: false, message: "--public-url must be an https URL" };
  }
  const link = await findSymlink(host, args.dataDir);
  if (link) return { ok: false, message: `refusing symlink at ${link}` };
  for (const rel of [
    "",
    "/tls",
    "/tls/server.key",
    "/tls/server.crt",
    "/tls/pin.json",
    "/admin.token",
    "/policy.json",
    "/meta.json",
    "/install-state.json",
  ]) {
    const stat = await host.lstat(rel ? `${args.dataDir}${rel}` : args.dataDir);
    if (stat?.type === "symlink")
      return { ok: false, message: `refusing symlink at ${args.dataDir}${rel}` };
  }
  const ancestor = await ancestorProblem(host, args.dataDir);
  if (ancestor) return { ok: false, message: ancestor };
  const dataStat = await host.lstat(args.dataDir);
  if (dataStat && dataStat.type !== "dir")
    return { ok: false, message: `${args.dataDir} is not a directory` };
  const loaded = await loadInstallState(host, args.dataDir);
  if (loaded.kind === "invalid") return { ok: false, message: loaded.message };
  const legacyMarker = await hasLegacyFiles(host, args.dataDir);
  if (legacyMarker && (loaded.kind === "absent" || loaded.kind === "mismatch")) {
    return {
      ok: false,
      message: `existing 0.x data in ${args.dataDir}; run nmzp migrate before nmzp install`,
    };
  }
  if (loaded.kind === "mismatch") {
    return { ok: false, message: `install-state.json dataDir does not match ${args.dataDir}` };
  }
  const tls = await inspectTls(host, args.dataDir);
  if (tls.state === "bad") return { ok: false, message: tls.message };
  if (publicHost && tls.state === "ready") {
    const cert = await host.readFile(`${args.dataDir}/tls/server.crt`);
    if (cert && !certificateCovers(cert.toString("utf8"), publicHost)) {
      return {
        ok: false,
        message: `certificate_address_mismatch: ${publicHost} is not covered by the existing certificate; refusing to replace it`,
      };
    }
  }
  const free = await host.freeBytes(args.dataDir);
  if (!Number.isFinite(free) || free < MIN_INSTALL_FREE_BYTES) {
    return { ok: false, message: `need at least 1 GiB free on ${args.dataDir}` };
  }
  for (const port of INSTALL_PORTS) {
    if (!(await host.portFree(port))) return { ok: false, message: `port ${port} is not free` };
  }
  return { ok: true };
}

async function execute(args: InstallArgs, io: InstallIo): Promise<number> {
  let secret: string | undefined;
  let marked = false;
  try {
    const loaded = await loadInstallState(io.host, args.dataDir);
    if (loaded.kind === "invalid") throw new InstallError(loaded.message);
    if (loaded.kind === "mismatch") {
      throw new InstallError(`install-state.json dataDir does not match ${args.dataDir}`);
    }
    const accounts = await ensureAccounts(io.host, { allowCreate: loaded.kind === "absent" });
    if (
      loaded.kind === "ok" &&
      (loaded.state.uid !== accounts.uid || loaded.state.gid !== accounts.gid)
    ) {
      throw new InstallError(
        `install-state uid/gid ${loaded.state.uid}/${loaded.state.gid} does not match the nmzp account ${accounts.uid}/${accounts.gid}`,
      );
    }
    await stopIfUnitPresent(io.host);
    await ensureStateDir(io.host);
    const createdData = await ensureChain(io.host, args.dataDir);
    io.stdout(`data dir: ${createdData ? `created ${args.dataDir}` : "skip"}\n`);
    const fixed = await fixDataPermissions(io.host, args.dataDir, accounts.uid, accounts.gid);
    const permission = accounts.created ? "created user nmzp" : fixed ? "corrected" : "skip";
    io.stdout(`permissions: ${permission}\n`);
    let state = loaded.kind === "ok" ? loaded.state : null;
    if (!state) {
      state = {
        v: 1,
        installer: INSTALLER,
        dataDir: args.dataDir,
        prefix: args.prefix,
        publicUrl: args.publicUrl ?? null,
        uid: accounts.uid,
        gid: accounts.gid,
        tokenShown: false,
        serviceEnabled: false,
      };
      await writeState(io.host, state);
    }
    marked = true;
    const material = await ensureMaterial(io, args, accounts.uid, accounts.gid);
    secret = material.token;
    io.stdout(`identity: ${material.tls} fingerprint ${material.fingerprint}\n`);
    io.stdout(`store: ${material.store}\n`);
    if (material.token) {
      secret = material.token;
      io.stdout(`admin token: ${material.token}\n`);
      if (!state.tokenShown) {
        state.tokenShown = true;
        await writeState(io.host, state, material.token);
      }
      io.stdout("admin: created\n");
    } else if (!state.tokenShown) {
      const existing = await io.host.readFile(`${args.dataDir}/admin.token`);
      const token = existing?.toString("utf8").trim() ?? "";
      if (!token) throw new InstallError("admin token missing");
      secret = token;
      io.stdout(`admin token: ${token}\n`);
      state.tokenShown = true;
      await writeState(io.host, state, token);
      io.stdout("admin: created\n");
    } else {
      io.stdout("admin: skip\n");
    }
    await writeUnit(io, args);
    const reloaded = await io.host.run(SYSTEMCTL, ["daemon-reload"]);
    if (reloaded.status !== 0) throw new InstallError("systemctl daemon-reload failed");
    const enabled = await io.host.run(SYSTEMCTL, ["enable", "--now", "nmzp"]);
    if (enabled.status !== 0) throw new InstallError("systemctl enable --now nmzp failed");
    const publicUrl = args.publicUrl ?? null;
    if (!state.serviceEnabled || state.prefix !== args.prefix || state.publicUrl !== publicUrl) {
      state.serviceEnabled = true;
      state.prefix = args.prefix;
      state.publicUrl = publicUrl;
      await writeState(io.host, state, secret);
    }
    io.stdout("start: systemctl daemon-reload; systemctl enable --now nmzp\n");
    io.stdout(`${ADMIN_HINT}\n${CA_HINT}\n`);
    await emitDoctor(io, args, secret);
    return 0;
  } catch (error) {
    const message = error instanceof Error ? error.message : "install failed";
    io.stderr(`${scrub(message, secret)}\n`);
    if (marked) {
      try {
        await emitDoctor(io, args, secret);
      } catch (doctorError) {
        const text = doctorError instanceof Error ? doctorError.message : "doctor failed";
        io.stderr(`${scrub(text, secret)}\n`);
      }
    }
    return 1;
  }
}

async function ensureMaterial(
  io: InstallIo,
  args: InstallArgs,
  uid: number,
  gid: number,
): Promise<{
  fingerprint: string;
  tls: "created" | "skip";
  store: "initialized" | "skip";
  token?: string;
}> {
  const dataDir = args.dataDir;
  const tlsBefore = await inspectTls(io.host, dataDir);
  if (tlsBefore.state === "bad") throw new InstallError(tlsBefore.message);
  const policyReady = (await io.host.lstat(`${dataDir}/policy.json`))?.type === "file";
  const tokenReady = (await io.host.lstat(`${dataDir}/admin.token`))?.type === "file";
  const metaReady = (await io.host.lstat(`${dataDir}/meta.json`))?.type === "file";
  const needStore = !policyReady || (!tokenReady && !metaReady);
  let issued: string | undefined;
  if (tlsBefore.state === "absent" || needStore) {
    const scratch = await io.host.generatorDir();
    let opened: { close(): Promise<void> } | undefined;
    try {
      if (tlsBefore.state === "absent") {
        const { loadOrCreateTls } = await import("./tls.ts");
        const material = await loadOrCreateTls(scratch, tlsHosts(args, io.env));
        const hostName = args.publicUrl ? httpsHost(args.publicUrl) : undefined;
        if (hostName && !certificateCovers(material.certPem, hostName)) {
          throw new InstallError(
            `certificate_address_mismatch: ${hostName} is not covered by the generated certificate`,
          );
        }
      }
      if (needStore) {
        const { NmzpStore, bootstrapAdmin } = await import("./persist.ts");
        const { loadMonitor } = await import("./paths.ts");
        const monitor = await loadMonitor(io.coreDir);
        const suggested = Array.isArray(monitor.privacy.SUGGESTED_PRIVACY)
          ? (monitor.privacy.SUGGESTED_PRIVACY as CustomPrivacyRule[])
          : [];
        const store = new NmzpStore(scratch);
        opened = store;
        await store.load({
          defaultRules: suggested,
          defaultOverrides: monitor.SUGGESTED_OVERRIDES,
          policySource: monitor,
          storageMode: "window",
        });
        if (!tokenReady) {
          const admin = await bootstrapAdmin(store);
          issued = admin.token;
        }
      }
      if (opened) {
        await opened.close();
        opened = undefined;
      }
      await copyGenerated(scratch, dataDir, io.host, uid, gid);
    } finally {
      if (opened) await opened.close().catch(() => undefined);
      await io.host.discardGeneratorDir(scratch);
    }
    await fixDataPermissions(io.host, dataDir, uid, gid);
  }
  if (!tokenReady && metaReady) {
    if (!issued) issued = newSecret(32);
    if ((await io.host.lstat(`${dataDir}/admin.token`))?.type !== "file") {
      await writeOwned(io.host, `${dataDir}/admin.token`, `${issued}\n`, 0o600, uid, gid);
    }
    await patchAdminHash(io.host, dataDir, issued, uid, gid);
  } else if (tokenReady) {
    const existing = (await io.host.readFile(`${dataDir}/admin.token`))?.toString("utf8").trim() ?? "";
    if (!existing) throw new InstallError("admin token missing");
    const metaStat = await io.host.lstat(`${dataDir}/meta.json`);
    if (!metaStat) {
      const body = `${JSON.stringify({ adminTokenHash: sha256Hex(existing), tickets: [] }, null, 2)}\n`;
      if (body.includes(existing)) throw new InstallError("refusing to persist admin token");
      await writeOwned(io.host, `${dataDir}/meta.json`, body, 0o600, uid, gid);
    } else if (metaStat.type !== "file") {
      throw new InstallError(`${dataDir}/meta.json is not a regular file`);
    } else if (await adminHashMissing(io.host, dataDir)) {
      await patchAdminHash(io.host, dataDir, existing, uid, gid);
    }
  }
  const tlsAfter = await inspectTls(io.host, dataDir);
  if (tlsAfter.state === "bad") throw new InstallError(tlsAfter.message);
  if (tlsAfter.state !== "ready") throw new InstallError("tls certificate missing");
  return {
    fingerprint: tlsAfter.fingerprint,
    tls: tlsBefore.state === "ready" ? "skip" : "created",
    store: policyReady ? "skip" : "initialized",
    token: tokenReady ? undefined : issued,
  };
}

async function writeUnit(io: InstallIo, args: InstallArgs): Promise<void> {
  const template = await readFile(join(io.coreDir, "nmzp.service"), "utf8");
  const next = renderServiceUnit(template, { dataDir: args.dataDir, prefix: args.prefix });
  const current = await io.host.readFile(UNIT_PATH);
  if (current && current.toString("utf8") === next) {
    io.stdout("service: skip\n");
    return;
  }
  for (const dir of ["/etc", "/etc/systemd", "/etc/systemd/system"]) {
    const stat = await io.host.lstat(dir);
    if (stat?.type === "symlink") throw new InstallError(`refusing symlink at ${dir}`);
    if (stat && stat.type !== "dir") throw new InstallError(`${dir} is not a directory`);
    if (!stat) await createDir(io.host, dir, 0o755, 0, 0);
    else {
      if (stat.uid !== 0 || (stat.mode & 0o022) !== 0) {
        throw new InstallError(
          `refusing ancestor ${dir}: must be root-owned and not group/world writable`,
        );
      }
      await openDirVerified(io.host, dir, stat);
    }
  }
  if (current) {
    const backup = `${UNIT_PATH}.bak-${io.host.now()}`;
    if (await io.host.lstat(backup)) throw new InstallError(`unit backup already exists: ${backup}`);
    await io.host.rename(UNIT_PATH, backup);
    io.stdout(`service: backup ${backup}\n`);
  }
  await writeOwned(io.host, UNIT_PATH, next, 0o644, 0, 0);
  io.stdout(`service: wrote ${UNIT_PATH}\n`);
}

async function emitDoctor(
  io: InstallIo,
  args: InstallArgs,
  secret: string | undefined,
): Promise<void> {
  const { formatDoctorText, runDoctor } = await import("./doctor/run.ts");
  const dataDir = io.host.resolve(args.dataDir);
  const home = io.host.resolve("/var/lib/nmzp-install-doctor-home");
  const report = await runDoctor({
    dataDir,
    home,
    env: {
      NMZP_DATA: dataDir,
      NMZP_STORAGE_MODE: "window",
      ...(args.publicUrl ? { NMZP_PUBLIC_URL: args.publicUrl } : {}),
    },
  });
  const text = scrub(formatDoctorText(report), secret);
  io.stdout(`doctor:\n${text.endsWith("\n") ? text : `${text}\n`}`);
}

function planLines(args: InstallArgs): string[] {
  return [
    "plan: preflight ok",
    "plan: systemctl stop nmzp if the unit already exists",
    `plan: mkdir ${args.dataDir} mode 0700`,
    "plan: create system user nmzp if absent",
    "plan: chmod 0700 directories and 0600 files, owner nmzp",
    "plan: generate CA and server certificate if tls material is absent",
    "plan: initialize store if policy.json is absent",
    "plan: generate admin token once on execute",
    `plan: write ${INSTALL_STATE_PATH}`,
    `plan: write ${UNIT_PATH}`,
    "plan: systemctl daemon-reload",
    "plan: systemctl enable --now nmzp",
    "plan: run doctor",
    `plan: ${ADMIN_HINT}`,
    `plan: ${CA_HINT}`,
  ];
}

async function stopIfUnitPresent(host: InstallHost): Promise<void> {
  const unit = await host.lstat(UNIT_PATH);
  if (!unit) return;
  if (unit.type !== "file") throw new InstallError(`${UNIT_PATH} is not a regular file`);
  const stopped = await host.run(SYSTEMCTL, ["stop", "nmzp"]);
  if (stopped.status !== 0) throw new InstallError("systemctl stop nmzp failed");
}

async function ensureChain(host: InstallHost, dataDir: string): Promise<boolean> {
  const parts = chain(dataDir);
  let created = false;
  for (const dir of parts) {
    const stat = await host.lstat(dir);
    if (stat?.type === "symlink") throw new InstallError(`refusing symlink at ${dir}`);
    if (stat && stat.type !== "dir") throw new InstallError(`${dir} is not a directory`);
    const leaf = dir === dataDir;
    if (!stat) {
      await createDir(host, dir, leaf ? 0o700 : 0o755, 0, 0);
      if (leaf) created = true;
      continue;
    }
    if (!leaf && (stat.uid !== 0 || (stat.mode & 0o022) !== 0)) {
      throw new InstallError(
        `refusing ancestor ${dir}: must be root-owned and not group/world writable`,
      );
    }
    await openDirVerified(host, dir, stat);
  }
  return created;
}

async function ensureStateDir(host: InstallHost): Promise<void> {
  for (const dir of ["/etc", INSTALL_STATE_DIR]) {
    const mode = dir === INSTALL_STATE_DIR ? 0o700 : 0o755;
    const stat = await host.lstat(dir);
    if (stat?.type === "symlink") throw new InstallError(`refusing symlink at ${dir}`);
    if (stat && stat.type !== "dir") throw new InstallError(`${dir} is not a directory`);
    if (!stat) {
      await createDir(host, dir, mode, 0, 0);
      continue;
    }
    if (stat.uid !== 0 || (stat.mode & 0o022) !== 0) {
      throw new InstallError(
        `refusing ancestor ${dir}: must be root-owned and not group/world writable`,
      );
    }
    if (dir === INSTALL_STATE_DIR && ((stat.mode & 0o777) !== 0o700 || stat.gid !== 0)) {
      await tighten(host, dir, "dir", 0o700, 0, 0);
    } else {
      await openDirVerified(host, dir, stat);
    }
  }
}

async function ensureAccounts(
  host: InstallHost,
  opts: { allowCreate: boolean },
): Promise<{ uid: number; gid: number; created: boolean }> {
  let created = false;
  let group = await host.run(GETENT, ["group", "nmzp"]);
  if (group.status !== 0) {
    if (!opts.allowCreate) throw new InstallError("account_conflict: primary group");
    const added = await host.run(GROUPADD, ["--system", "nmzp"]);
    if (added.status !== 0) throw new InstallError("groupadd nmzp failed");
    created = true;
  }
  let passwd = await host.run(GETENT, ["passwd", "nmzp"]);
  if (passwd.status !== 0) {
    if (!opts.allowCreate) throw new InstallError("account_conflict: nmzp user is absent");
    const added = await host.run(USERADD, [...NMZP_USERADD_ARGS]);
    if (added.status !== 0) throw new InstallError("useradd nmzp failed");
    created = true;
  }
  if (created) {
    group = await host.run(GETENT, ["group", "nmzp"]);
    passwd = await host.run(GETENT, ["passwd", "nmzp"]);
  }
  if (group.status !== 0 || passwd.status !== 0) {
    throw new InstallError("account_conflict: nmzp account is incomplete");
  }
  const parsedGroup = parseGroup(group.stdout);
  const parsedUser = parsePasswd(passwd.stdout);
  if (!parsedGroup || !parsedUser) throw new InstallError("account_conflict: nmzp account is incomplete");
  assertNmzpAccount(parsedUser, parsedGroup);
  return { uid: parsedUser.uid, gid: parsedGroup.gid, created };
}

function assertNmzpAccount(passwd: PasswdRow, group: GroupRow): void {
  if (
    !isSystemAccountId(passwd.uid) ||
    !isSystemAccountId(passwd.gid) ||
    !isSystemAccountId(group.gid)
  ) {
    throw new InstallError("account_conflict: system id range");
  }
  if (!NMZP_SHELLS.has(passwd.shell)) throw new InstallError("account_conflict: shell");
  if (group.name !== "nmzp" || passwd.gid !== group.gid) {
    throw new InstallError("account_conflict: primary group");
  }
}

async function fixDataPermissions(
  host: InstallHost,
  dataDir: string,
  uid: number,
  gid: number,
): Promise<boolean> {
  let changed = false;
  if (await host.lstat(dataDir)) changed = await tighten(host, dataDir, "dir", 0o700, uid, gid);
  const tlsDir = `${dataDir}/tls`;
  if (await host.lstat(tlsDir))
    changed = (await tighten(host, tlsDir, "dir", 0o700, uid, gid)) || changed;
  for (const name of DATA_FILES) {
    const path = `${dataDir}/${name}`;
    if (await host.lstat(path))
      changed = (await tighten(host, path, "file", 0o600, uid, gid)) || changed;
  }
  for (const name of TLS_FILES) {
    const path = `${tlsDir}/${name}`;
    if (await host.lstat(path))
      changed = (await tighten(host, path, "file", 0o600, uid, gid)) || changed;
  }
  return changed;
}

async function tighten(
  host: InstallHost,
  path: string,
  kind: "file" | "dir",
  mode: number,
  uid: number,
  gid: number,
): Promise<boolean> {
  const stat = await host.lstat(path);
  if (!stat || stat.type !== kind) throw new InstallError(`${path} is not a ${kind}`);
  const handle =
    kind === "dir"
      ? await host.openDir(path)
      : await host.openFile(path, { write: false, create: false, exclusive: false, mode });
  try {
    const st = await handle.stat();
    if (st.type !== kind || st.dev !== stat.dev || st.ino !== stat.ino) {
      throw new InstallError(`inode changed at ${path}`);
    }
    let changed = false;
    if ((st.mode & 0o777) !== mode) {
      await handle.chmod(mode);
      changed = true;
    }
    if (st.uid !== uid || st.gid !== gid) {
      await handle.chown(uid, gid);
      changed = true;
    }
    return changed;
  } finally {
    await handle.close();
  }
}

async function createDir(
  host: InstallHost,
  path: string,
  mode: number,
  uid: number,
  gid: number,
): Promise<void> {
  await host.mkdir(path, mode);
  const created = await host.lstat(path);
  if (!created || created.type !== "dir") throw new InstallError(`${path} is not a directory`);
  const handle = await host.openDir(path);
  try {
    const st = await handle.stat();
    if (st.type !== "dir" || st.dev !== created.dev || st.ino !== created.ino) {
      throw new InstallError(`inode changed at ${path}`);
    }
    if ((st.mode & 0o777) !== (mode & 0o777)) await handle.chmod(mode & 0o777);
    if (st.uid !== uid || st.gid !== gid) await handle.chown(uid, gid);
  } finally {
    await handle.close();
  }
}

async function openDirVerified(host: InstallHost, path: string, before: HostStat): Promise<void> {
  const handle = await host.openDir(path);
  try {
    const st = await handle.stat();
    if (st.type !== "dir" || st.dev !== before.dev || st.ino !== before.ino) {
      throw new InstallError(`inode changed at ${path}`);
    }
  } finally {
    await handle.close();
  }
}

async function writeOwned(
  host: InstallHost,
  path: string,
  data: Buffer | string,
  mode: number,
  uid: number,
  gid: number,
): Promise<void> {
  const before = await host.lstat(path);
  if (before?.type === "symlink") throw new InstallError(`refusing symlink at ${path}`);
  if (before && before.type !== "file") throw new InstallError(`${path} is not a file`);
  const handle = await host.openFile(path, {
    write: true,
    create: !before,
    exclusive: !before,
    mode,
  });
  try {
    const st = await handle.stat();
    if (st.type !== "file") throw new InstallError(`${path} is not a file`);
    if (before && (st.dev !== before.dev || st.ino !== before.ino)) {
      throw new InstallError(`inode changed at ${path}`);
    }
    await handle.write(data);
    if ((st.mode & 0o777) !== (mode & 0o777)) await handle.chmod(mode & 0o777);
    if (st.uid !== uid || st.gid !== gid) await handle.chown(uid, gid);
    await handle.fsync();
  } finally {
    await handle.close();
  }
}

async function readVerified(host: InstallHost, path: string): Promise<Buffer | null> {
  const before = await host.lstat(path);
  if (!before) return null;
  if (before.type === "symlink") throw new InstallError(`refusing symlink at ${path}`);
  if (before.type !== "file") throw new InstallError(`not a file: ${path}`);
  const handle = await host.openFile(path, {
    write: false,
    create: false,
    exclusive: false,
    mode: before.mode,
  });
  try {
    const st = await handle.stat();
    if (st.type !== "file" || st.dev !== before.dev || st.ino !== before.ino) {
      throw new InstallError(`inode changed at ${path}`);
    }
    return await handle.read();
  } finally {
    await handle.close();
  }
}

async function copyGenerated(
  scratch: string,
  dataDir: string,
  host: InstallHost,
  uid: number,
  gid: number,
): Promise<void> {
  await copyDir(scratch, dataDir, host, uid, gid);
}

async function copyDir(
  from: string,
  logicalDir: string,
  host: InstallHost,
  uid: number,
  gid: number,
): Promise<void> {
  const entries = await readdir(from, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith(".") || entry.name === "incomplete.json") continue;
    const dest = `${logicalDir}/${entry.name}`;
    if (entry.isDirectory()) {
      const stat = await host.lstat(dest);
      if (stat?.type === "symlink") throw new InstallError(`refusing symlink at ${dest}`);
      if (!stat) await createDir(host, dest, 0o700, uid, gid);
      else if (stat.type !== "dir") throw new InstallError(`${dest} is not a directory`);
      else await openDirVerified(host, dest, stat);
      await copyDir(join(from, entry.name), dest, host, uid, gid);
      continue;
    }
    if (!entry.isFile()) continue;
    const existing = await host.lstat(dest);
    if (existing?.type === "symlink") throw new InstallError(`refusing symlink at ${dest}`);
    // Never replace meta.json, admin.token, or tls material that is already present.
    if (existing) continue;
    const body = await readFile(join(from, entry.name));
    await writeOwned(host, dest, body, 0o600, uid, gid);
  }
}

async function writeState(host: InstallHost, state: InstallState, secret?: string): Promise<void> {
  const body = stateBody(state);
  if (secret && body.includes(secret)) throw new InstallError("refusing to persist admin token");
  await ensureStateDir(host);
  const tmp = `${INSTALL_STATE_PATH}.${randomUUID()}.tmp`;
  await writeOwned(host, tmp, body, 0o600, 0, 0);
  try {
    await host.rename(tmp, INSTALL_STATE_PATH, true);
  } catch (error) {
    await host.remove(tmp);
    throw error;
  }
}

async function loadInstallState(host: InstallHost, dataDir: string): Promise<LoadedState> {
  const stat = await host.lstat(INSTALL_STATE_PATH);
  if (!stat) return { kind: "absent" };
  if (stat.type !== "file") {
    return { kind: "invalid", message: `refusing non-regular ${INSTALL_STATE_PATH}` };
  }
  if (stat.uid !== 0 || stat.gid !== 0 || (stat.mode & 0o777) !== 0o600) {
    return { kind: "invalid", message: "install-state.json is not root-owned mode 0600" };
  }
  const raw = await host.readFile(INSTALL_STATE_PATH);
  if (!raw) return { kind: "invalid", message: "install-state.json is invalid" };
  const parsed = parseState(raw.toString("utf8"));
  if (!parsed) return { kind: "invalid", message: "install-state.json is invalid" };
  if (parsed.dataDir !== dataDir) return { kind: "mismatch", dataDir: parsed.dataDir };
  return { kind: "ok", state: parsed };
}

function parseState(raw: string): InstallState | null {
  try {
    const value = JSON.parse(raw) as Partial<InstallState>;
    if (value.v !== 1 || value.installer !== INSTALLER) return null;
    if (typeof value.dataDir !== "string" || !isSafeAbs(value.dataDir)) return null;
    if (typeof value.prefix !== "string" || !isSafeAbs(value.prefix)) return null;
    if (!(value.publicUrl === null || typeof value.publicUrl === "string")) return null;
    if (!Number.isInteger(value.uid) || !Number.isInteger(value.gid)) return null;
    if ((value.uid ?? 0) <= 0 || (value.gid ?? 0) <= 0) return null;
    if (typeof value.tokenShown !== "boolean" || typeof value.serviceEnabled !== "boolean")
      return null;
    return {
      v: 1,
      installer: INSTALLER,
      dataDir: value.dataDir,
      prefix: value.prefix,
      publicUrl: value.publicUrl,
      uid: value.uid ?? 0,
      gid: value.gid ?? 0,
      tokenShown: value.tokenShown,
      serviceEnabled: value.serviceEnabled,
    };
  } catch {
    return null;
  }
}

function stateBody(state: InstallState): string {
  return `${JSON.stringify(
    {
      v: state.v,
      installer: state.installer,
      dataDir: state.dataDir,
      prefix: state.prefix,
      publicUrl: state.publicUrl,
      uid: state.uid,
      gid: state.gid,
      tokenShown: state.tokenShown,
      serviceEnabled: state.serviceEnabled,
    },
    null,
    2,
  )}\n`;
}

async function hasLegacyFiles(host: InstallHost, dataDir: string): Promise<boolean> {
  const admin = await host.lstat(`${dataDir}/admin.token`);
  const policy = await host.lstat(`${dataDir}/policy.json`);
  return admin?.type === "file" || policy?.type === "file";
}

type TlsInspection =
  | { state: "absent" }
  | { state: "ready"; fingerprint: string }
  | { state: "bad"; message: string };

async function inspectTls(host: InstallHost, dataDir: string): Promise<TlsInspection> {
  let present = 0;
  for (const name of TLS_FILES) {
    const stat = await host.lstat(`${dataDir}/tls/${name}`);
    if (!stat) continue;
    if (stat.type !== "file") {
      return { state: "bad", message: `tls/${name} is not a regular file; refusing to replace it` };
    }
    present += 1;
  }
  if (present === 0) return { state: "absent" };
  if (present !== TLS_FILES.length) {
    return {
      state: "bad",
      message: "tls material is incomplete; refusing to replace existing certificate files",
    };
  }
  const key = await host.readFile(`${dataDir}/tls/server.key`);
  const cert = await host.readFile(`${dataDir}/tls/server.crt`);
  const pin = await host.readFile(`${dataDir}/tls/pin.json`);
  if (!key || !cert || !pin) {
    return {
      state: "bad",
      message: "tls material is incomplete; refusing to replace existing certificate files",
    };
  }
  const problem = tlsMaterialProblem(cert.toString("utf8"), key.toString("utf8"), pin.toString("utf8"));
  if (problem) return { state: "bad", message: problem };
  return { state: "ready", fingerprint: fingerprintSha256Pem(cert.toString("utf8")) };
}

function tlsMaterialProblem(certPem: string, keyPem: string, pinRaw: string): string | null {
  try {
    const cert = new X509Certificate(certPem);
    const key = createPrivateKey(keyPem);
    if (!cert.checkPrivateKey(key)) {
      return "tls key does not match certificate; refusing to replace it";
    }
  } catch {
    return "tls key does not match certificate; refusing to replace it";
  }
  let pin: { fingerprintSha256?: unknown };
  try {
    pin = JSON.parse(pinRaw) as { fingerprintSha256?: unknown };
  } catch {
    return "tls pin mismatch; refusing to replace certificate files";
  }
  let fingerprint = "";
  try {
    fingerprint = fingerprintSha256Pem(certPem);
  } catch {
    return "tls key does not match certificate; refusing to replace it";
  }
  if (pin.fingerprintSha256 !== fingerprint) {
    return "tls pin mismatch; refusing to replace certificate files";
  }
  return null;
}

async function adminHashMissing(host: InstallHost, dataDir: string): Promise<boolean> {
  const raw = await host.readFile(`${dataDir}/meta.json`);
  if (!raw) return true;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw.toString("utf8"));
  } catch {
    throw new InstallError("meta.json is corrupt");
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new InstallError("meta.json is corrupt");
  }
  const record = parsed as { adminTokenHash?: unknown; tickets?: unknown };
  if ("tickets" in record && !Array.isArray(record.tickets)) {
    throw new InstallError("meta.json tickets are corrupt");
  }
  return typeof record.adminTokenHash !== "string" || record.adminTokenHash.length === 0;
}

async function patchAdminHash(
  host: InstallHost,
  dataDir: string,
  token: string,
  uid: number,
  gid: number,
): Promise<void> {
  const path = `${dataDir}/meta.json`;
  const existing = await host.readFile(path);
  if (!existing) throw new InstallError("meta.json is missing");
  const next = replaceAdminTokenHash(existing.toString("utf8"), sha256Hex(token));
  if (next.includes(token)) throw new InstallError("refusing to persist admin token");
  await writeOwned(host, path, next, 0o600, uid, gid);
}

function replaceAdminTokenHash(raw: string, hash: string): string {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new InstallError("meta.json is corrupt");
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new InstallError("meta.json is corrupt");
  }
  const record = parsed as Record<string, unknown>;
  if ("tickets" in record && !Array.isArray(record.tickets)) {
    throw new InstallError("meta.json tickets are corrupt");
  }
  record.adminTokenHash = hash;
  return `${JSON.stringify(record, null, 2)}\n`;
}

async function ancestorProblem(host: InstallHost, path: string): Promise<string | null> {
  for (const dir of ancestorPaths(path)) {
    const stat = await host.lstat(dir);
    if (!stat) continue;
    if (stat.type === "symlink") return `refusing symlink at ${dir}`;
    if (stat.type !== "dir" || stat.uid !== 0 || (stat.mode & 0o022) !== 0) {
      return `refusing ancestor ${dir}: must be root-owned and not group/world writable`;
    }
  }
  return null;
}

async function findSymlink(host: InstallHost, path: string): Promise<string | null> {
  for (const dir of chain(path)) {
    const stat = await host.lstat(dir);
    if (stat?.type === "symlink") return dir;
  }
  return null;
}

function tlsHosts(args: InstallArgs, env: NodeJS.ProcessEnv): string[] {
  const extra = (env.NMZP_TLS_HOSTS ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
  const host = args.publicUrl ? httpsHost(args.publicUrl) : undefined;
  return [...extra, ...(host ? [host] : [])];
}

function httpsHost(raw: string): string | undefined {
  try {
    const url = new URL(raw);
    if (url.protocol !== "https:" || !url.hostname || url.username || url.password) return undefined;
    return url.hostname;
  } catch {
    return undefined;
  }
}

function chain(path: string): string[] {
  const out: string[] = [];
  let current = "";
  for (const part of logical(path).split("/")) {
    if (!part) continue;
    current += `/${part}`;
    out.push(current);
  }
  return out;
}

function ancestorPaths(path: string): string[] {
  const parts = chain(path);
  parts.pop();
  return ["/", ...parts];
}

function logical(path: string): string {
  if (!path.startsWith("/")) throw new InstallError("absolute path required");
  const parts: string[] = [];
  for (const part of path.split("/")) {
    if (!part || part === ".") continue;
    if (part === "..") throw new InstallError("path escapes root");
    parts.push(part);
  }
  return `/${parts.join("/")}`;
}

function isSafeAbs(path: string): boolean {
  if (!path.startsWith("/") || path.length < 2 || path.endsWith("/")) return false;
  if (/[\0\r\n\t ]/.test(path)) return false;
  const parts = path.split("/").slice(1);
  return parts.every(
    (part) => part.length > 0 && part !== "." && part !== ".." && /^[A-Za-z0-9._-]+$/.test(part),
  );
}

function parseGroup(text: string): GroupRow | null {
  const parts = firstLine(text).split(":");
  if (parts.length < 3 || parts[0] !== "nmzp") return null;
  const gid = strictId(parts[2] ?? "");
  if (gid === null) return null;
  return { name: "nmzp", gid };
}

function parsePasswd(text: string): PasswdRow | null {
  const parts = firstLine(text).split(":");
  if (parts.length < 7 || parts[0] !== "nmzp") return null;
  const uid = strictId(parts[2] ?? "");
  const gid = strictId(parts[3] ?? "");
  if (uid === null || gid === null) return null;
  return { uid, gid, shell: parts[6] ?? "" };
}

function strictId(text: string): number | null {
  if (!/^[0-9]+$/.test(text)) return null;
  const value = Number(text);
  return Number.isSafeInteger(value) ? value : null;
}

function firstLine(text: string): string {
  return (text.split("\n", 1)[0] ?? "").replace(/\r$/, "");
}

function replaceLine(text: string, prefix: string, line: string): string {
  const pattern = new RegExp(`^${prefix}.*$`, "m");
  if (!pattern.test(text)) throw new InstallError(`unit template missing ${prefix}`);
  return text.replace(pattern, line);
}

function scrub(text: string, secret: string | undefined): string {
  if (!secret) return text;
  return text.split(secret).join("[redacted]");
}

function sameArgs(args: readonly string[], expected: readonly string[]): boolean {
  return args.length === expected.length && expected.every((arg, index) => arg === args[index]);
}

function statOf(node: FsNode): HostStat {
  return {
    type: node.type,
    mode: node.mode,
    uid: node.uid,
    gid: node.gid,
    dev: node.dev,
    ino: node.ino,
    special: node.special,
  };
}

function toHostStat(stat: {
  isSymbolicLink(): boolean;
  isDirectory(): boolean;
  isFile(): boolean;
  mode: number;
  uid: number;
  gid: number;
  dev: number;
  ino: number;
}): HostStat {
  const type = stat.isSymbolicLink()
    ? "symlink"
    : stat.isDirectory()
      ? "dir"
      : stat.isFile()
        ? "file"
        : "other";
  return {
    type,
    mode: stat.mode & 0o777,
    uid: stat.uid,
    gid: stat.gid,
    dev: stat.dev,
    ino: stat.ino,
    special: stat.mode & 0o7000,
  };
}

function linuxFileFlags(flags: OpenFileFlags): number {
  const nofollow = linuxFlag("O_NOFOLLOW", constants.O_NOFOLLOW);
  let bits = (flags.write ? constants.O_WRONLY : constants.O_RDONLY) | nofollow;
  if (flags.create) bits |= constants.O_CREAT;
  if (flags.exclusive) bits |= constants.O_EXCL;
  return bits;
}

function linuxDirFlags(): number {
  return (
    constants.O_RDONLY |
    linuxFlag("O_DIRECTORY", constants.O_DIRECTORY) |
    linuxFlag("O_NOFOLLOW", constants.O_NOFOLLOW)
  );
}

function linuxFlag(name: string, value: number | undefined): number {
  if (process.platform !== "linux" || typeof value !== "number") {
    throw new InstallError(`${name} is unavailable`);
  }
  return value;
}

function mapOpenError(path: string, error: unknown): Error {
  const code =
    error && typeof error === "object" && "code" in error
      ? String((error as { code?: unknown }).code)
      : "";
  if (code === "ELOOP" || code === "ENOTDIR") return new InstallError(`refusing symlink at ${path}`);
  if (code === "EEXIST") return new InstallError(`refusing existing path ${path}`);
  return error instanceof Error ? error : new InstallError(`open failed for ${path}`);
}

function isSeedPath(path: string): boolean {
  return path.startsWith("/tmp/nmzp-install-seed-") && !path.slice("/tmp/".length).includes("/");
}
