import type { AgentDef, AgentId, CanonicalTool } from "./types";

export const AGENTS: Record<AgentId, AgentDef> = {
  zcode: {
    id: "zcode",
    name: "ZCode",
    vendor: "Z.ai / GLM",
    process: "zcode",
    hookPath: "~/.zcode/cli/config.json",
    projectHookPath: ".zcode/config.json",
    models: ["glm-4.6", "glm-4.5-air", "glm-4.5"],
    transcriptHint: "~/.zcode/cli/log/",
    letter: "Z",
  },
  codex: {
    id: "codex",
    name: "Codex",
    vendor: "OpenAI",
    process: "codex",
    hookPath: "~/.codex/hooks.json",
    projectHookPath: ".codex/hooks.json",
    models: ["gpt-5-codex", "o3", "gpt-4.1"],
    transcriptHint: "~/.codex/sessions/",
    letter: "C",
  },
  grok: {
    id: "grok",
    name: "Grok",
    vendor: "xAI",
    process: "grok",
    hookPath: "~/.grok/hooks/*.json",
    projectHookPath: ".grok/hooks/*.json",
    models: ["grok-code", "grok-4.6", "grok-build"],
    transcriptHint: "~/.grok/grok.db",
    letter: "G",
  },
  claude: {
    id: "claude",
    name: "Claude Code",
    vendor: "Anthropic",
    process: "claude",
    hookPath: "~/.claude/settings.json",
    projectHookPath: ".claude/settings.json",
    models: ["claude-sonnet-4", "claude-opus-4", "claude-haiku"],
    transcriptHint: "~/.claude/projects/",
    letter: "A",
  },
  antigravity: {
    id: "antigravity",
    name: "Antigravity",
    vendor: "Google",
    process: "antigravity",
    hookPath: "~/.gemini/config/hooks.json",
    projectHookPath: ".agents/hooks.json",
    models: ["gemini-3-pro", "gemini-3-flash"],
    transcriptHint: "~/.gemini/antigravity/brain/",
    letter: "A",
  },
  kimi: {
    id: "kimi",
    name: "Kimi Code",
    vendor: "Moonshot AI",
    process: "kimi",
    hookPath: "~/.kimi-code/config.toml",
    projectHookPath: "(none)",
    models: ["kimi-k2"],
    transcriptHint: "~/.kimi-code/",
    letter: "K",
  },
  qoder: {
    id: "qoder",
    name: "Qoder",
    vendor: "Alibaba",
    process: "qoder",
    hookPath: "~/.qoder/settings.json",
    projectHookPath: ".qoder/settings.json",
    models: ["qwen3-coder"],
    transcriptHint: "~/.qoder/",
    letter: "Q",
  },
  lingma: {
    id: "lingma",
    name: "通义灵码 / Qoder CN",
    vendor: "Alibaba",
    process: "lingma",
    hookPath: "~/.lingma/settings.json",
    projectHookPath: ".lingma/settings.json",
    models: ["qwen3-coder"],
    transcriptHint: "~/.lingma/",
    letter: "L",
  },
  codebuddy: {
    id: "codebuddy",
    name: "CodeBuddy",
    vendor: "Tencent",
    process: "codebuddy",
    hookPath: "~/.codebuddy/settings.json",
    projectHookPath: ".codebuddy/settings.json",
    models: ["hunyuan"],
    transcriptHint: "~/.codebuddy/",
    letter: "B",
  },
  cursor: {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    process: "cursor-agent",
    hookPath: "~/.cursor/hooks.json",
    projectHookPath: ".cursor/hooks.json",
    models: ["cursor-small", "claude-sonnet-4", "gpt-5"],
    transcriptHint: "~/.cursor/projects/",
    letter: "R",
  },
  copilot: {
    id: "copilot",
    name: "Copilot",
    vendor: "GitHub",
    process: "copilot",
    hookPath: "~/.copilot/hooks.json",
    projectHookPath: ".copilot/hooks.json",
    models: ["gpt-5-codex", "gpt-4.1"],
    transcriptHint: "~/.copilot/session/",
    letter: "P",
  },
  windsurf: {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    process: "windsurf-agent",
    hookPath: "~/.codeium/hooks.json",
    projectHookPath: ".windsurf/hooks.json",
    models: ["cascade", "gemini-2.5-pro"],
    transcriptHint: "~/.codeium/windsurf/",
    letter: "W",
  },
  gemini: {
    id: "gemini",
    name: "Gemini CLI",
    vendor: "Google",
    process: "gemini",
    hookPath: "~/.gemini/settings.json",
    projectHookPath: ".gemini/hooks.json",
    models: ["gemini-2.5-pro", "gemini-2.5-flash"],
    transcriptHint: "~/.gemini/tmp/",
    letter: "M",
  },
  aider: {
    id: "aider",
    name: "Aider",
    vendor: "Aider",
    process: "aider",
    hookPath: "~/.aider/hooks.json",
    projectHookPath: ".aider/hooks.json",
    models: ["deepseek-v3", "claude-sonnet-4", "gpt-4.1"],
    transcriptHint: ".aider.chat.history.md",
    letter: "D",
  },
  qwen: {
    id: "qwen",
    name: "Qwen Code",
    vendor: "Alibaba",
    process: "qwen-code",
    hookPath: "~/.qwen/settings.json",
    projectHookPath: ".qwen/hooks.json",
    models: ["qwen3-coder", "qwen-max"],
    transcriptHint: "~/.qwen/log/",
    letter: "Q",
  },
  cline: {
    id: "cline",
    name: "Cline",
    vendor: "Cline",
    process: "cline",
    hookPath: "~/.cline/hooks.json",
    projectHookPath: ".cline/hooks.json",
    models: ["claude-sonnet-4", "deepseek-v3"],
    transcriptHint: "~/.cline/tasks/",
    letter: "L",
  },
  trae: {
    id: "trae",
    name: "Trae",
    vendor: "ByteDance",
    process: "trae-agent",
    hookPath: "~/.trae/hooks.json",
    projectHookPath: ".trae/hooks.json",
    models: ["doubao-seed", "deepseek-v3"],
    transcriptHint: "~/.trae/logs/",
    letter: "T",
  },
};

export const AGENT_ORDER: AgentId[] = [
  "zcode",
  "codex",
  "grok",
  "claude",
  "antigravity",
  "kimi",
  "qoder",
  "lingma",
  "codebuddy",
  "cursor",
  "copilot",
  "windsurf",
  "gemini",
  "qwen",
  "aider",
  "cline",
  "trae",
];

export const PRIMARY_AGENTS: AgentId[] = ["zcode", "codex", "grok"];

export const AGENT_IDS = new Set<string>(AGENT_ORDER);

const NATIVE_TOOL_MAP: Record<string, CanonicalTool> = {
  bash: "Bash",
  shell: "Bash",
  shell_command: "Bash",
  exec_command: "Bash",
  run_terminal_command: "Bash",
  run_command: "Bash",
  read: "Read",
  view_file: "Read",
  list_dir: "Glob",
  find_by_name: "Glob",
  read_file: "Read",
  write: "Write",
  write_file: "Write",
  write_to_file: "Write",
  edit: "Edit",
  edit_file: "Edit",
  replace_file_content: "Edit",
  multi_replace_file_content: "MultiEdit",
  apply_patch: "Edit",
  strreplace: "Edit",
  str_replace: "Edit",
  search_replace: "Edit",
  multiedit: "MultiEdit",
  glob: "Glob",
  grep: "Grep",
  grep_search: "Grep",
  webfetch: "WebFetch",
  read_url_content: "WebFetch",
  websearch: "WebSearch",
  search_web: "WebSearch",
  search_x: "WebSearch",
  web_search: "WebSearch",
  task: "Task",
  agent: "Task",
  delegate: "Task",
  spawn_subagent: "Task",
  invoke_subagent: "Task",
  skill: "Skill",
  runcommand: "Bash",
  run_shell_command: "Bash",
  run_in_terminal: "Bash",
  create_file: "Write",
  replace: "Edit",
  delete: "Bash",
  fetchurl: "WebFetch",
  web_fetch: "WebFetch",
  google_web_search: "WebSearch",
  list_directory: "Glob",
  read_many_files: "Read",
  invoke_agent: "Task",
};

export function normalizeTool(native: string): CanonicalTool {
  const key = native.toLowerCase();
  if (key.startsWith("mcp__")) return "MCP";
  return NATIVE_TOOL_MAP[key] ?? "Bash";
}

export function agentLabel(id: AgentId) {
  return AGENTS[id].name;
}

export function isAgentId(v: string): v is AgentId {
  return AGENT_IDS.has(v);
}
