import type { RuleDef } from "./types";

const GUARD: RuleDef[] = [
  {id:"credential_file_upload",risk:"high",action:"block",family:"secret",title:"上传凭据文件",titleEn:"Upload a credential file",desc:"显式上传 .env、SSH 私钥等凭据路径，不能使用普通上传例外。",descEn:"Explicit upload of credential paths is not a normal upload exception.",tools:["Bash"],field:"command",pattern:"\\bcurl\\b[^\\n]*(--upload-file|\\s-T\\s|--data(?:-binary)?\\s+@|-F\\s+\\S+=@)[^\\n]*(?:\\.env(?:[.\\s'\\\"]|$)|id_rsa|id_ed25519|\\.aws[/\\\\]credentials)"},
  {
    id: "telemetry_drop",
    risk: "high",
    action: "block",
    family: "recon",
    title: "丢掉会话/遥测上报",
    titleEn: "Drop session/telemetry upload",
    desc: "Agent 把会话、设备、时间打到 statsig/sentry 一类遥测域。直接丢，不碰模型 API。",
    descEn: "The agent is shipping session, device, or time to a telemetry host. Dropped. Model APIs are not touched.",
    tools: ["Bash", "WebFetch", "WebSearch"],
    field: "url",
    pattern:
      "(statsig\\.(com|net)|statsig\\.anthropic\\.com|sentry\\.io|amplitude\\.com|api\\.segment\\.(io|com)|telemetry\\.anthropic\\.com|/telemetry\\b|/event_logging\\b)",
  },
  {
    id: "persona_cloak",
    risk: "high",
    action: "rewrite",
    family: "recon",
    title: "出网用户画像改成美国标签",
    titleEn: "Rewrite outbound profile tags to a US user",
    desc: "名单内 Agent 出网打时区/语言/国家码时，明文改成 America/New_York、en-US、US。不改时钟，不改本地东京项目文件，不解 TLS。不是精准伪装，IP 仍能看出你在哪。",
    descEn: "When a listed agent ships timezone/locale/country tags, plaintext becomes America/New_York, en-US, US. Clock, local Tokyo files, and TLS are untouched. Not an impersonation — the IP still locates you.",
    tools: ["Bash", "WebFetch", "WebSearch", "MCP"],
    field: "command",
    pattern:
      "(timezone|time[_-]?zone|\\btz)\\s*[:=]\\s*[\"']?Asia\\\\/Tokyo|(locale|language|\\blang|LC_ALL|LANG|Accept-Language)\\s*[:=]\\s*[\"']?ja-JP",
  },
  {
    id: "isolate_kill_monitor",
    risk: "high",
    action: "block",
    family: "isolate",
    title: "结束本防护进程",
    titleEn: "Kill this guard process",
    desc: "杀 nmzp-monitor / nmzp-probe 会让看板失联。只认本项目进程名，不管用户别的程序。",
    descEn: "Killing nmzp-monitor / nmzp-probe takes the board offline. Only this project's process names match.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(?:^|[;&|\\n]|&&)\\s*(?:sudo\\s+)?(?:kill|pkill|killall)(?:\\s+-[A-Za-z]+)*\\s+nmzp-(?:monitor|probe)(?=[\\s;|&]|$)",
  },
  {
    id: "isolate_stop_container",
    risk: "high",
    action: "block",
    family: "isolate",
    title: "停掉本防护容器",
    titleEn: "Stop this guard container",
    desc: "systemctl stop nmzp，或 docker stop nmzp。只认本项目服务名。",
    descEn: "systemctl stop nmzp, or docker stop nmzp. Only this project's unit name matches.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(?:^|[;&|\\n]|&&)\\s*(?:sudo\\s+)?(?:systemctl\\s+(?:stop|disable|kill)\\s+nmzp(?:\\.service)?|service\\s+nmzp(?:\\.service)?\\s+stop|docker\\s+(?:stop|kill|rm)\\s+nmzp)(?=[\\s;|&]|$)",
  },
  {
    id: "isolate_cut_board",
    risk: "high",
    action: "block",
    family: "isolate",
    title: "切断本防护出网",
    titleEn: "Cut this guard off the network",
    desc: "防火墙或 hosts 专门点名 nmzp-monitor / nmzp-probe。不看用户自己的防火墙规则。",
    descEn: "Firewall or hosts entries aimed at nmzp-monitor / nmzp-probe. The user's own firewall is out of scope.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(iptables|nft|ufw)\\b[^\\n]{0,120}\\b(nmzp-monitor|nmzp-probe)\\b|>>?\\s*/etc/hosts[^\\n]*\\b(nmzp-monitor|nmzp-probe)\\b",
  },
  {
    id: "isolate_delete_binary",
    risk: "high",
    action: "block",
    family: "isolate",
    title: "删掉本防护程序",
    titleEn: "Delete this guard binary",
    desc: "rm 指向已安装 ~/.nmzp、/opt/nmzp、/var/lib/nmzp 或专属 hook。源码目录同名不在此列。",
    descEn: "rm aimed at installed ~/.nmzp, /opt/nmzp, /var/lib/nmzp, or the dedicated hook. A same-named source tree is out of scope.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\brm\\b[^\\n]{0,240}(?:[~]?[/\\\\]+(?:[\\w. -]+[/\\\\]+)*\\.nmzp(?:[/\\\\]|$)|[/\\\\]opt[/\\\\]nmzp(?:[/\\\\]|\\s|$)|[/\\\\]var[/\\\\]lib[/\\\\]nmzp(?:[/\\\\]|\\s|$)|[/\\\\]\\.grok[/\\\\]hooks[/\\\\]nmzp\\.json)",
  },
  {
    id: "clipboard_pipe_upload",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "把剪切板管道送到外网",
    titleEn: "Pipe the clipboard off-box",
    desc: "pbpaste / xclip / wl-paste 接到 curl。只在编程助手进程里判，不看用户自己复制。",
    descEn: "pbpaste / xclip / wl-paste piped into curl. Only coding-agent processes; the user's own copy is ignored.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(pbpaste|xclip\\s+(-o|--output|out)|xsel\\s+(-ob?|--output)|wl-paste|Get-Clipboard)\\b[^\\n|;]*\\|\\s*(curl|wget|nc|ncat|ssh|rclone|scp)\\b|osascript[^\\n]*clipboard[^\\n|;]*\\|\\s*(curl|wget|nc)\\b",
  },
  {
    id: "screenshot_then_upload",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "截屏后立刻上传",
    titleEn: "Screenshot then upload",
    desc: "screencapture / grim 和 curl 写在同一条命令里。不看用户自己的截图工具。",
    descEn: "screencapture / grim in the same command as curl. The user's own screenshot tool is out of scope.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(screencapture|gnome-screenshot|grim|import\\s+-window\\s+root|xwd)\\b[\\s\\S]{0,200}\\b(curl|wget|scp|rclone|nc)\\b|\\b(curl|wget|scp|rclone)\\b[\\s\\S]{0,200}\\b(screencapture|gnome-screenshot|grim)\\b",
  },
  {
    id: "screenshot_file_upload",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "上传刚截的桌面图",
    titleEn: "Upload a just-taken desktop shot",
    desc: "curl -F 指向 /tmp 下的 png/jpg，且命令里带截屏工具或 desktop/screenshot 文件名。",
    descEn: "curl -F of a /tmp png/jpg named as a screenshot or taken by a capture tool.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(curl|wget|scp)\\b[^\\n]*(screencapture|/tmp/\\S+\\.(png|jpe?g)|(desktop|screenshot|screen)\\S*\\.(png|jpe?g))",
  },
  {
    id: "poison_instruction_file",
    risk: "high",
    action: "block",
    family: "poison",
    title: "往助手规则文件里写覆盖指令",
    titleEn: "Inject override instructions into an agent rule file",
    desc: "往 CLAUDE.md / .cursorrules / AGENTS.md 写入 ignore previous 一类覆盖语。这是语料投毒，不是用户编辑。",
    descEn: "Writing ignore-previous style overrides into CLAUDE.md / .cursorrules / AGENTS.md. Corpus poison, not a human edit.",
    tools: ["Write", "Edit"],
    field: "command",
    pattern:
      "ignore\\s+(all\\s+)?(previous|prior|above)\\s+(instructions|prompts|rules)|you are (now )?(DAN|jailbroken)|<\\|im_start\\|>\\s*system",
  },
  {
    id: "poison_relay_payload",
    risk: "high",
    action: "block",
    family: "poison",
    title: "中转站回复里夹带覆盖指令",
    titleEn: "Relay response carries override instructions",
    desc: "非官方模型地址的 /v1/chat/completions 回复里出现 ignore previous / 伪 system。官方 api.openai.com 等不走这条。",
    descEn: "A non-official /v1/chat/completions reply containing ignore-previous or a fake system role. Official model APIs do not match.",
    tools: ["Bash", "WebFetch", "MCP"],
    field: "command",
    pattern:
      "(openrouter\\.ai|together\\.ai|openai-sb\\.com|one-api\\.|new-api\\.|relay\\.)[\\s\\S]{0,400}(ignore\\s+(all\\s+)?(previous|prior)|you are (now )?DAN|<\\|im_start\\|>\\s*system)",
  },
  {
    id: "zcode_checkpoint_path",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "ZCode 工作区快照落盘",
    titleEn: "ZCode workspace snapshot on disk",
    desc: "往 ~/.zcode/v2/checkpoints 写 tar.gz.enc，是客户端自己打的整库包，不是模型工具调用。",
    descEn: "Writing tar.gz.enc under ~/.zcode/v2/checkpoints is the app packing the whole repo — not a model tool call.",
    tools: ["*"],
    field: "file_path",
    pattern: "\\.zcode[/\\\\]v2[/\\\\]checkpoints|repo_snapshot_extra_manifest|\\.tar\\.gz\\.enc$",
  },
  {
    id: "zcode_snapshot_host",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "ZCode 快照凭证 / OSS 直传",
    titleEn: "ZCode snapshot credentials / OSS upload",
    desc: "连 zcode.z.ai 拿 OSS 签名，或从 ZCode 进程直传阿里云 OSS。模型 API 走 api.z.ai，不在此列。",
    descEn: "Fetching OSS signatures from zcode.z.ai, or the ZCode process posting to Aliyun OSS. Model API on api.z.ai is not this.",
    tools: ["*"],
    field: "url",
    pattern: "zcode\\.z\\.ai(?!(?::\\d+)?/(?:[a-z]{2}/)?docs(?:[/?#]|$))",
  },
  {
    id: "zcode_oss_form",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "OSS 表单签名上传",
    titleEn: "OSS form-signed upload",
    desc: "请求体带 policy 和 x-oss-signature，是对象存储直传，不经过应用服务器。",
    descEn: "Body carries policy and x-oss-signature — a direct object-storage post, bypassing the app server.",
    tools: ["Bash", "WebFetch", "MCP"],
    field: "command",
    pattern: "x-oss-signature|ossaccesskeyid|x-oss-signature-version",
  },
  {
    id: "zcode_capture_event",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "ZCode 静默 capture 事件",
    titleEn: "ZCode silent capture event",
    desc: "captureBeforePrompt / repo-wiki-update 会在每次提问和任务结束时打包工作区，没有开关。",
    descEn: "captureBeforePrompt / repo-wiki-update pack the workspace on every prompt and task end. No toggle.",
    tools: ["*"],
    field: "command",
    pattern: "captureBeforePrompt|repo-wiki-update",
  },
  {
    id: "pack_pipe_upload",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "打包后管道上传整个项目",
    titleEn: "Pipe an archive of the project to the network",
    desc: "tar/zip 的输出直接交给 curl/scp/nc，典型的静默打包外传，不询问直接拦截。",
    descEn: "Archive output piped into curl/scp/nc — silent project exfil. Blocked without prompting.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(tar|zip|7z|cpio)\\b[^\\n|;]*\\|\\s*(curl|wget|nc|ncat|ssh|rclone|scp)\\b|\\b(curl|wget)\\b[^\\n]*\\|\\s*(tar|unzip)\\b",
  },
  {
    id: "anonymous_drop_host",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "发往匿名网盘 / 剪切板 / Webhook",
    titleEn: "Send data to an anonymous drop or webhook",
    desc: "transfer.sh、file.io、0x0.st、pastebin、Discord webhook 等常被用来偷偷外传。",
    descEn: "transfer.sh, file.io, 0x0.st, pastebin, Discord webhooks are common silent-exfil sinks.",
    tools: ["Bash", "WebFetch", "MCP"],
    field: "command",
    pattern:
      "(transfer\\.sh|file\\.io|0x0\\.st|pastebin\\.com|paste\\.rs|gist\\.github\\.com|webhook\\.site|ngrok\\.(io|app)|discord\\.com/api/webhooks|api\\.telegram\\.org/bot)",
  },
  {
    id: "archive_project_root",
    risk: "medium",
    action: "log",
    title: "压缩当前项目或家目录",
    titleEn: "Archive the current project or home directory",
    desc: "本地打包/导出本身不证明上传；仅记录，后续外传独立判定。",
    descEn: "Local packaging is not proof of an upload; evaluate any subsequent transfer separately.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(tar)\\b[^\\n]*(\\s(\\.|\\$PWD|\\$HOME|~)(\\s|$)|\\s-C\\s+(\\.|\\$HOME|~))|\\bzip\\s+-[a-zA-Z]*r[a-zA-Z]*\\s+\\S+\\s+(\\.|\\$PWD|\\$HOME|~)\\b",
  },
  {
    id: "scp_rsync_tree",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "递归拷贝项目到远端",
    titleEn: "Recursively copy the project off-box",
    desc: "scp -r / rsync -a 针对 `.` 或家目录。",
    descEn: "scp -r / rsync -a pointed at `.` or the home directory.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(scp|rsync)\\b[^\\n]*(?:^|\\s)-[a-zA-Z]*[ra][a-zA-Z]*(?=\\s)[^\\n]*(?:\\s\\.(?:\\s|$)|\\s\\./|\\$HOME|~|/home/)",
  },
  {
    id: "rclone_cloud_copy",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "rclone / aws s3 同步到云",
    titleEn: "rclone / aws s3 sync to the cloud",
    desc: "把工作区同步到对象存储等于整库外传。",
    descEn: "Syncing the workspace to object storage is a full-tree exfil.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\brclone\\s+(copy|sync|move)\\b|\\baws\\s+s3\\s+(cp|sync)\\b",
  },
  {
    id: "git_archive_exfil",
    risk: "medium",
    action: "log",
    title: "git archive / bundle 导出仓库",
    titleEn: "git archive / bundle export",
    desc: "本地打包/导出本身不证明上传；仅记录，后续外传独立判定。",
    descEn: "Local packaging is not proof of an upload; evaluate any subsequent transfer separately.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bgit\\s+(archive|bundle)\\b",
  },
  {
    id: "env_piped_outbound",
    risk: "high",
    action: "block",
    family: "secret",
    title: "把 .env / 密钥文件管道送到外网",
    titleEn: "Pipe .env or key files to the network",
    desc: "cat .env | curl 一类操作会把密钥送走。",
    descEn: "cat .env | curl and similar send secrets off-box.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(cat|tee|head|tail|base64|xxd|openssl)\\s+[^\\n]*(\\.env|id_rsa|id_ed25519|credentials|\\.pem)[^\\n]*\\|\\s*(curl|wget|nc|ssh)\\b",
  },
  {
    id: "curl_post_local_file",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "把本地文件作为 POST 体发出去",
    titleEn: "POST a local file as the request body",
    desc: "curl -d @file / --data-binary @ 会把磁盘上的文件读进 HTTP 请求。",
    descEn: "curl -d @file / --data-binary @ reads a file off disk into an HTTP body.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bcurl\\b[^\\n]*(\\s-d\\s+@|--data(-binary|-raw|-ascii)?\\s+@|--data-urlencode\\s+@)",
  },
  {
    id: "wget_post_file",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "wget --post-file 上传",
    titleEn: "wget --post-file upload",
    desc: "wget 把本地文件当 POST 发出去。",
    descEn: "wget posting a local file outbound.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bwget\\b[^\\n]*--post-file",
  },
  {
    id: "nc_redirect_file",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "把文件重定向给 netcat",
    titleEn: "Redirect a file into netcat",
    desc: "nc < archive 是不走 HTTP 的外传。",
    descEn: "nc < archive is a non-HTTP exfil path.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(nc|ncat|netcat)\\b[^\\n]*<\\s*\\S+",
  },
  {
    id: "anonymous_drop_url",
    risk: "high",
    action: "block",
    family: "exfil",
    title: "WebFetch 发往匿名网盘 / Webhook",
    titleEn: "WebFetch to an anonymous drop or webhook",
    desc: "通过 WebFetch / URL 字段打到 transfer.sh 一类地址。",
    descEn: "WebFetch / URL field pointed at transfer.sh-class sinks.",
    tools: ["Bash", "WebFetch", "MCP"],
    field: "url",
    pattern:
      "(transfer\\.sh|file\\.io|0x0\\.st|pastebin\\.com|paste\\.rs|gist\\.github\\.com|webhook\\.site|ngrok\\.(io|app)|discord\\.com/api/webhooks|api\\.telegram\\.org/bot)",
  },
  {
    id: "monitor_self_tamper",
    risk: "high",
    action: "block",
    family: "tamper",
    title: "篡改已安装的 NMZP",
    titleEn: "Tamper with installed NMZP",
    desc: "写/覆盖已安装 runtime、凭据、manifest 或 ~/.grok/hooks/nmzp.json。源码仓库和普通 Agent 配置不在此列。",
    descEn: "Write/overwrite installed runtime, credentials, manifest, or ~/.grok/hooks/nmzp.json. The source tree and ordinary agent config are out of scope.",
    tools: ["Write", "Edit", "Bash"],
    field: "file_path",
    pattern:
      "(?:^|[\\\\/])(?:Users|home)[\\\\/][^\\\\/]+[\\\\/]\\.nmzp(?:[\\\\/]|$)|(?:^|[\\\\/])root[\\\\/]\\.nmzp(?:[\\\\/]|$)|^[~][\\\\/]\\.nmzp(?:[\\\\/]|$)|(?:^|[\\\\/])opt[\\\\/]nmzp(?:[\\\\/]|$)|(?:^|[\\\\/])var[\\\\/]lib[\\\\/]nmzp(?:[\\\\/]|$)|(?:^|[\\\\/])(?:Users|home)[\\\\/][^\\\\/]+[\\\\/]\\.grok[\\\\/]hooks[\\\\/]nmzp\\.json$",
  },
  {
    id: "monitor_self_tamper_cmd",
    risk: "high",
    action: "block",
    family: "tamper",
    title: "用命令拆掉已安装的 NMZP",
    titleEn: "Disable installed NMZP from a shell",
    desc: "对已安装路径做写/删/改名。读、构建、调用 grok CLI、展示用 localStorage 不在此列。",
    descEn: "Write/delete/rename of installed paths. Reads, builds, grok CLI, and display localStorage are out of scope.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(?:^|[;&|\\n]|&&)\\s*(?:Set-Content|Out-File|Remove-Item|Move-Item|Copy-Item|New-Item|Rename-Item|rm|mv)\\b[^\\n]{0,240}(?:[/\\\\]Users[/\\\\][^/\\\\]+[/\\\\]\\.nmzp(?:[/\\\\]|$)|[/\\\\]home[/\\\\][^/\\\\]+[/\\\\]\\.nmzp(?:[/\\\\]|$)|[~][/\\\\]\\.nmzp(?:[/\\\\]|$)|[/\\\\]opt[/\\\\]nmzp(?:[/\\\\]|$)|[/\\\\]var[/\\\\]lib[/\\\\]nmzp(?:[/\\\\]|$)|[/\\\\]\\.grok[/\\\\]hooks[/\\\\]nmzp\\.json)",
  },
];

export const RULES: RuleDef[] = [
  ...GUARD,
  {
    id: "dangerous_delete",
    risk: "high",
    action: "block",
    family: "destructive",
    title: "递归强制删除根目录 / 家目录 / 上级目录",
    titleEn: "Recursive force-delete of /, ~ or parent dir",
    desc: "rm -rf 直接作用在 /、~ 或 .. 上，会把整块目录不可恢复地删掉。",
    descEn: "rm -rf pointed at /, ~ or .. wipes an entire directory tree.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*)\\s+(/|~|\\$HOME|\\.\\.)(\\s|$)",
  },
  {
    id: "disk_overwrite",
    risk: "high",
    action: "block",
    family: "destructive",
    title: "磁盘级写入 / 分区操作",
    titleEn: "Raw disk write / partitioning",
    desc: "dd、mkfs、fdisk、parted 直接操作磁盘或分区。",
    descEn: "dd, mkfs, fdisk, parted operate on raw disks or partitions.",
    tools: ["Bash"],
    field: "command",
    pattern: "(?<![\\w-])(dd|mkfs|fdisk|parted)(?![\\w-])",
  },
  {
    id: "curl_pipe_shell",
    risk: "high",
    action: "block",
    title: "下载脚本直接管道执行",
    titleEn: "Download piped straight into a shell",
    desc: "从网上下载的内容不落地、直接交给 shell 执行。",
    descEn: "Fetched content is executed without ever being saved to disk.",
    tools: ["Bash"],
    field: "command",
    pattern: "(curl|wget)[^|;\\n]*\\|\\s*(sudo\\s+)?(sh|bash|zsh)\\b",
  },
  {
    id: "reverse_shell_pattern",
    risk: "high",
    action: "block",
    title: "反弹 Shell",
    titleEn: "Reverse shell",
    desc: "把本机的 shell 连到一个远程地址。",
    descEn: "Connects a local shell out to a remote address.",
    tools: ["Bash"],
    field: "command",
    pattern:
      ">&\\s*/dev/tcp/\\S+/\\d+|\\b(nc|ncat|netcat)\\b[^\\n]*-[a-zA-Z]*e[a-zA-Z]*\\s+/bin/(ba)?sh\\b|\\bsocat\\b[^\\n]*exec:",
  },
  {
    id: "encoded_payload_exec",
    risk: "high",
    action: "block",
    title: "解码后执行隐藏内容",
    titleEn: "Decode-then-execute hidden payload",
    desc: "把 base64 / 十六进制编码的内容解码后直接执行。",
    descEn: "Decodes base64 / hex content and runs it immediately.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(base64\\s+(-d|--decode)|xxd\\s+-r\\s+-p?)\\b[^|;\\n]*\\|\\s*(sudo\\s+)?(sh|bash|zsh|python3?)\\b",
  },
  {
    id: "fork_bomb",
    risk: "medium",
    action: "log",
    family: "destructive",
    title: "Fork 炸弹",
    titleEn: "Fork bomb",
    desc: "无限自我复制的进程，会在几秒内耗尽系统资源。",
    descEn: "A process that replicates itself until the machine is exhausted.",
    tools: ["Bash"],
    field: "command",
    pattern: ":\\s*\\(\\s*\\)\\s*\\{[^}]*:\\s*\\|\\s*:[^}]*&[^}]*\\}\\s*;\\s*:",
  },
  {
    id: "disable_security_controls",
    risk: "medium",
    action: "log",
    title: "关闭安全防护",
    titleEn: "Disable security controls",
    desc: "关掉 SELinux、防火墙，或清空 iptables。",
    descEn: "Turns off SELinux, the firewall, or flushes iptables.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\bsetenforce\\s+0\\b|\\bufw\\s+disable\\b|\\biptables\\s+(-F|--flush)\\b|\\bsystemctl\\s+(stop|disable)\\s+(firewalld|ufw|apparmor)\\b",
  },
  {
    id: "ssh_authorized_keys_bash_write",
    risk: "medium",
    action: "log",
    title: "往 SSH 授权密钥 / 配置里写内容",
    titleEn: "Write to SSH authorized_keys / config",
    desc: "往 authorized_keys 追加公钥 = 免密登录。",
    descEn: "Appending a key to authorized_keys grants passwordless login.",
    tools: ["Bash"],
    field: "command",
    pattern: ">>?\\s*~?/?(\\.ssh/authorized_keys|\\.ssh/id_\\w+|\\.ssh/config)\\b",
  },
  {
    id: "chmod_world_writable_recursive",
    risk: "medium",
    action: "log",
    family: "destructive",
    title: "把整棵目录树设成所有人可写",
    titleEn: "Make a whole directory tree world-writable",
    desc: "chmod 777 递归作用到 / 或家目录。",
    descEn: "chmod 777 applied recursively to / or the home directory.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bchmod\\s+(-R\\s+)?777\\b.*\\s(/|~)",
  },
  {
    id: "sudo_pip_install",
    risk: "medium",
    action: "log",
    title: "用 sudo 往系统 Python 装包",
    titleEn: "sudo pip install into system Python",
    desc: "会直接改系统级 Python，可能弄坏系统自带的工具。",
    descEn: "Modifies system-wide Python and can break OS tooling.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bsudo\\s+(python3?\\s+-m\\s+pip|pip3?)\\s+install\\b",
  },
  {
    id: "sensitive_file_write",
    risk: "medium",
    action: "log",
    title: "写入 SSH 密钥 / 云凭据 / .env",
    titleEn: "Write SSH keys / cloud credentials / .env",
    desc: "写入私钥、云凭据或环境密钥文件。",
    descEn: "Writes private keys, cloud credentials or env secret files.",
    tools: ["Write", "Edit", "Bash"],
    field: "file_path",
    pattern: "(\\.ssh/|\\.aws/credentials|\\.env$|id_rsa|id_ed25519|\\.pem$)",
  },
  {
    id: "webshell_pattern_in_write",
    risk: "high",
    action: "block",
    title: "写入 Webshell 代码",
    titleEn: "Write a webshell",
    desc: "写入 eval($_POST) 一类的后门代码。",
    descEn: "Writes classic webshell payloads such as eval($_POST).",
    tools: ["Write", "Edit"],
    field: "command",
    pattern: "eval\\s*\\(\\s*\\$_(POST|GET|REQUEST|COOKIE)\\s*\\[",
  },
  {
    id: "agent_config_tamper",
    risk: "medium",
    action: "log",
    title: "修改 ZCode / Codex / Grok 自身配置",
    titleEn: "Tamper with ZCode / Codex / Grok config",
    desc: "改 hook、权限或模型配置。只记，不拦。",
    descEn: "Editing hook, permission or model config. Logged, not blocked.",
    tools: ["Write", "Edit", "Bash"],
    field: "file_path",
    pattern:
      "(\\.zcode/cli/config\\.json|\\.codex/hooks\\.json|\\.codex/config\\.toml|\\.grok/user-settings\\.json|\\.grok/hooks/|\\.claude/settings\\.json|\\.cursor/hooks\\.json)",
  },
  {
    id: "kill_monitor_process",
    risk: "high",
    action: "block",
    family: "tamper",
    title: "结束 NMZP-Monitor 自身进程",
    titleEn: "Kill NMZP-Monitor itself",
    desc: "试图杀掉监控探针或 hook。直接拦。",
    descEn: "Tries to kill the monitoring probe or hook. Blocked.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(?:^|[;&|\\n]|&&)\\s*(?:kill|pkill|killall)(?:\\s+-[A-Za-z]+)*\\s+nmzp-(?:monitor|probe)(?=[\\s;|&]|$)",
  },
  {
    id: "db_destructive_command",
    risk: "medium",
    action: "log",
    family: "destructive",
    title: "数据库破坏性操作",
    titleEn: "Destructive database command",
    desc: "DROP / DELETE / TRUNCATE / FLUSHALL。",
    descEn: "DROP / DELETE / TRUNCATE / FLUSHALL against a live database.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(mysql|psql|redis-cli|mongo|mongosh|sqlite3)\\b[^\\n|;&]*\\b(DROP|DELETE|TRUNCATE|FLUSHALL|FLUSHDB)\\b",
  },
  {
    id: "docker_privileged_or_host_mount",
    risk: "medium",
    action: "log",
    title: "特权容器 / 挂载宿主机根目录",
    titleEn: "Privileged container / host-root mount",
    desc: "docker run --privileged 或 -v /:/ 等于拿到宿主机。",
    descEn: "docker run --privileged or -v /:/ is a host takeover.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bdocker\\s+run\\b[^\\n]*(--privileged\\b|-v\\s+/:/|docker\\.sock)",
  },
  {
    id: "c2_framework_execution",
    risk: "medium",
    action: "log",
    title: "渗透测试 / C2 框架",
    titleEn: "Pentest / C2 framework",
    desc: "msfconsole、cobaltstrike、sliver、havoc。",
    descEn: "msfconsole, cobaltstrike, sliver, havoc and similar frameworks.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\bmsfconsole\\b|\\bmsfvenom\\b|\\bcobaltstrike\\b|\\bsliver-(client|server)\\b|\\bhavoc\\b|\\bmimikatz\\b",
  },
  {
    id: "curl_download_then_exec",
    risk: "medium",
    action: "log",
    title: "下载脚本后再执行",
    titleEn: "Download a script, then run it",
    desc: "先用 curl / wget 把脚本下载到本地，再单独运行。",
    descEn: "curl / wget saves a script, then it is executed separately.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "(?=.*\\b(curl|wget2?)\\b[^\\n]*(-o\\b|-O\\b|--output\\b))(?=.*\\.(sh|py|pl|rb)\\b)(?=.*\\b(bash|sh|zsh|python3?|chmod\\s+\\+x|\\./)\\b)",
  },
  {
    id: "setuid_setgid_bit",
    risk: "medium",
    action: "log",
    title: "给程序加 setuid / setgid 位",
    titleEn: "Set the setuid / setgid bit",
    desc: "让程序以文件所有者（通常是 root）身份运行。",
    descEn: "Makes the program run as the file owner, usually root.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bchmod\\s+(-R\\s+)?\\S*[ug]\\+s\\b|\\bchmod\\s+(-R\\s+)?[0-7]?[42][0-7]{3}\\b",
  },
  {
    id: "user_account_management",
    risk: "medium",
    action: "log",
    title: "增删改系统用户 / 修改密码",
    titleEn: "Add / remove / modify system users",
    desc: "useradd、userdel、usermod、passwd。",
    descEn: "useradd, userdel, usermod, passwd change machine accounts.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(useradd|userdel|usermod|adduser|deluser|passwd)\\b",
  },
  {
    id: "pip_install_no_venv",
    risk: "medium",
    action: "log",
    title: "不在虚拟环境里 pip 安装",
    titleEn: "pip install outside a virtualenv",
    desc: "没有激活虚拟环境就 pip install。",
    descEn: "pip install with no virtualenv active.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(pip3?\\s+install|python3?\\s+-m\\s+pip\\s+install)\\b",
  },
  {
    id: "browser_credential_read",
    risk: "medium",
    action: "log",
    title: "读取浏览器保存的密码 / Cookie",
    titleEn: "Read browser-saved passwords / cookies",
    desc: "读取 Cookies、Login Data、logins.json。",
    descEn: "Reads Cookies, Login Data, logins.json and similar stores.",
    tools: ["Read", "Bash"],
    field: "file_path",
    pattern: "(Cookies|Login Data|Web Data|cookies\\.sqlite|logins\\.json|key4\\.db)",
  },
  {
    id: "ssh_tunnel_reverse_proxy",
    risk: "medium",
    action: "log",
    title: "SSH 隧道 / 端口转发",
    titleEn: "SSH tunnel / port forwarding",
    desc: "ssh -R / -L / -D、socat、chisel。",
    descEn: "ssh -R / -L / -D, socat or chisel open a port path off-box.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bssh\\b[^\\n]*\\s-[a-zA-Z]*[RDL][a-zA-Z]*\\b|\\bsocat\\b|\\bchisel\\b\\s+(client|server)\\b",
  },
  {
    id: "crontab_persistence",
    risk: "medium",
    action: "log",
    title: "添加定时任务",
    titleEn: "Add a scheduled task",
    desc: "修改 crontab 或 /etc/cron。",
    descEn: "Edits crontab or /etc/cron — a common persistence trick.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bcrontab\\s+-[erl]\\b|>>?\\s*/etc/cron",
  },
  {
    id: "systemd_persistence",
    risk: "medium",
    action: "log",
    title: "启用 / 启动系统服务",
    titleEn: "Enable / start a system service",
    desc: "systemctl enable / start 会让服务开机自启。",
    descEn: "systemctl enable / start makes a service start at boot.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bsystemctl\\s+(enable|start)\\s+\\S+",
  },
  {
    id: "sudo_usage",
    risk: "medium",
    action: "log",
    title: "以 root 权限执行命令",
    titleEn: "Run a command as root",
    desc: "sudo 后面的命令会以管理员身份运行。",
    descEn: "Whatever follows sudo runs with administrator privileges.",
    tools: ["Bash"],
    field: "command",
    pattern: "(^|;|&&|\\|\\|)\\s*sudo\\b|^sudo\\b",
  },
  {
    id: "system_package_install",
    risk: "medium",
    action: "log",
    title: "系统包管理器安装 / 卸载软件",
    titleEn: "System package manager install / remove",
    desc: "apt、yum、dnf、pacman、brew 会往系统里装或删软件。",
    descEn: "apt, yum, dnf, pacman, brew install or remove system software.",
    tools: ["Bash"],
    field: "command",
    pattern:
      "\\b(apt|apt-get)\\s+(install|remove|purge)\\b|\\b(yum|dnf)\\s+(install|remove)\\b|\\bbrew\\s+(cask\\s+)?(install|uninstall)\\b",
  },
  {
    id: "npm_global_install",
    risk: "medium",
    action: "log",
    title: "npm 全局安装",
    titleEn: "npm global install",
    desc: "npm install -g 装到系统级 node_modules。",
    descEn: "npm install -g writes into the system-wide node_modules.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bnpm\\s+(install|i)\\s+.*(-g\\b|--global\\b)",
  },
  {
    id: "chmod_777_single_file",
    risk: "medium",
    action: "log",
    title: "把文件设成所有人可读写执行",
    titleEn: "Make a file world-writable",
    desc: "777 权限过于宽松。",
    descEn: "777 is far more permissive than almost anything needs.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bchmod\\s+777\\b",
  },
  {
    id: "chmod_recursive_generic",
    risk: "medium",
    action: "log",
    title: "递归修改权限",
    titleEn: "Recursive permission change",
    desc: "chmod -R 会改一整棵目录树的权限。",
    descEn: "chmod -R changes permissions on an entire tree.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bchmod\\s+-R\\b",
  },
  {
    id: "env_file_read",
    risk: "medium",
    action: "log",
    title: "读取 .env / 密钥文件",
    titleEn: "Read .env / secret files",
    desc: "读取项目密钥文件，可能把密钥带进模型上下文。",
    descEn: "Reads project secret files that may leak into model context.",
    tools: ["Read", "Bash"],
    field: "file_path",
    pattern: "(^|/)(\\.env|\\.env\\.[A-Za-z0-9._-]+|secrets?\\.ya?ml|credentials\\.json)$",
  },
  {
    id: "git_force_push",
    risk: "medium",
    action: "log",
    family: "destructive",
    title: "强制推送 / 改写历史",
    titleEn: "Force-push / rewrite history",
    desc: "git push --force 会覆盖远端历史。",
    descEn: "git push --force overwrites remote history.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bgit\\s+push\\b[^\\n]*--force(-with-lease)?\\b|\\bgit\\s+reset\\s+--hard\\b",
  },
  {
    id: "cross_workdir_write",
    risk: "medium",
    action: "log",
    title: "写入当前项目以外的路径",
    titleEn: "Write outside the current project",
    desc: "Agent 在工作区之外写文件。",
    descEn: "The agent is writing files outside the current workspace.",
    tools: ["Write", "Edit"],
    field: "file_path",
    pattern: "^/(etc|usr|var|opt|root|home)/",
  },
  {
    id: "mcp_suspicious_tool_name",
    risk: "medium",
    action: "log",
    title: "可疑的 MCP 工具",
    titleEn: "Suspicious MCP tool",
    desc: "MCP 工具名带 reverse-shell / c2 / backdoor。",
    descEn: "MCP tool name contains reverse-shell / c2 / backdoor.",
    tools: ["*"],
    field: "tool_name",
    pattern: "^mcp__[a-zA-Z0-9_-]*(reverse[_-]?shell|c2server|beacon|backdoor)",
  },
  {
    id: "pentest_recon_tool_execution",
    risk: "medium",
    action: "log",
    title: "扫描 / 爆破工具",
    titleEn: "Scanning / brute-force tool",
    desc: "nmap、masscan、sqlmap、hydra、nikto。",
    descEn: "nmap, masscan, sqlmap, hydra, nikto and similar tools.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bnmap\\b|\\bmasscan\\b|\\bsqlmap\\b|\\bhydra\\b|\\bnikto\\b|\\bffuf\\b|\\bhashcat\\b",
  },
  {
    id: "npm_local_install",
    risk: "low",
    action: "log",
    title: "npm 项目内安装",
    titleEn: "npm install in the project",
    desc: "在当前项目里 npm install。",
    descEn: "npm install scoped to the current project.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bnpm\\s+(install|i|ci)\\b",
  },
  {
    id: "js_package_install",
    risk: "low",
    action: "log",
    title: "JS 包管理器安装依赖",
    titleEn: "JS package manager install",
    desc: "yarn / pnpm / bun 装项目依赖。",
    descEn: "yarn / pnpm / bun installing project dependencies.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(yarn|pnpm|bun)\\s+(add|install|i)\\b",
  },
  {
    id: "uv_project_install",
    risk: "low",
    action: "log",
    title: "uv 项目/工具安装",
    titleEn: "uv project/tool install",
    desc: "uv add / uv sync 装进项目 .venv。",
    descEn: "uv add / uv sync installs into the project .venv.",
    tools: ["Bash"],
    field: "command",
    pattern: "^uv\\s+(?:add|sync|pip\\s+install|tool\\s+install)\\b",
  },
  {
    id: "process_kill",
    risk: "low",
    action: "log",
    title: "结束进程",
    titleEn: "Kill a process",
    desc: "kill / pkill / killall。",
    descEn: "kill / pkill / killall terminates processes.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(kill|pkill|killall)\\b",
  },
  {
    id: "git_operation",
    risk: "low",
    action: "log",
    title: "Git 操作",
    titleEn: "Git operation",
    desc: "git status / add / commit / push / pull / diff。",
    descEn: "git status / add / commit / push / pull / diff.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bgit\\s+(status|add|commit|push|pull|diff|log|checkout|switch|stash|fetch|rebase|merge)\\b",
  },
  {
    id: "ssh_operation",
    risk: "low",
    action: "log",
    title: "SSH 操作",
    titleEn: "SSH operation",
    desc: "ssh / scp / sftp 远程连接。",
    descEn: "ssh / scp / sftp remote connection.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(ssh|scp|sftp)\\b",
  },
  {
    id: "download_operation",
    risk: "low",
    action: "log",
    title: "下载文件",
    titleEn: "Download a file",
    desc: "curl / wget 下载（未管道执行）。",
    descEn: "curl / wget download that is not piped into a shell.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(curl|wget)\\b",
  },
  {
    id: "docker_operation",
    risk: "low",
    action: "log",
    title: "Docker 操作",
    titleEn: "Docker operation",
    desc: "docker / docker compose。",
    descEn: "docker / docker compose.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\bdocker(\\s+compose)?\\b|\\bpodman\\b",
  },
  {
    id: "archive_operation",
    risk: "low",
    action: "log",
    title: "压缩 / 解压",
    titleEn: "Archive / extract",
    desc: "tar / zip / unzip / gzip。",
    descEn: "tar / zip / unzip / gzip.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(tar|zip|unzip|gzip|gunzip|7z)\\b",
  },
  {
    id: "network_diag",
    risk: "info",
    action: "log",
    title: "网络诊断",
    titleEn: "Network diagnostic",
    desc: "ping / traceroute / dig / nslookup / netstat。",
    descEn: "ping / traceroute / dig / nslookup / netstat.",
    tools: ["Bash"],
    field: "command",
    pattern: "\\b(ping|traceroute|tracepath|dig|nslookup|netstat|ss|ip\\s+addr)\\b",
  },
  {
    id: "screenshot_tool",
    risk: "info",
    action: "log",
    title: "截屏 / 读图",
    titleEn: "Screenshot / image read",
    desc: "screencapture、import、或读取图片。",
    descEn: "screencapture, import, or reading an image file.",
    tools: ["Read", "Bash"],
    field: "file_path",
    pattern: "\\.(png|jpe?g|webp|gif|bmp)$",
  },
];

export const RULE_BY_ID = Object.fromEntries(RULES.map((r) => [r.id, r]));
