/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as InstallRouteImport } from './routes/install'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TapRouteImport } from './routes/tap'
import { Route as ThreatsRouteImport } from './routes/threats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TapRoute = TapRouteImport.update({
  id: '/tap',
  path: '/tap',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/rights': typeof RightsRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/tap': typeof TapRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/rights': typeof RightsRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/tap': typeof TapRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/rights': typeof RightsRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/tap': typeof TapRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/install'
    | '/network'
    | '/rights'
    | '/rules'
    | '/status'
    | '/tap'
    | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/install'
    | '/network'
    | '/rights'
    | '/rules'
    | '/status'
    | '/tap'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/install'
    | '/network'
    | '/rights'
    | '/rules'
    | '/status'
    | '/tap'
    | '/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  InstallRoute: typeof InstallRoute
  NetworkRoute: typeof NetworkRoute
  RightsRoute: typeof RightsRoute
  RulesRoute: typeof RulesRoute
  StatusRoute: typeof StatusRoute
  TapRoute: typeof TapRoute
  ThreatsRoute: typeof ThreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap': {
      id: '/tap'
      path: '/tap'
      fullPath: '/tap'
      preLoaderRoute: typeof TapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  InstallRoute: InstallRoute,
  NetworkRoute: NetworkRoute,
  RightsRoute: RightsRoute,
  RulesRoute: RulesRoute,
  StatusRoute: StatusRoute,
  TapRoute: TapRoute,
  ThreatsRoute: ThreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
